### ISSUE TITLE
Selenium or related process fails to terminate after tests pass, causing Travis to fail

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1002]
Intermittent build failures are a result

**Comment by sogaani** [comment]
@hobinjk
Probably, this is caused by the Gateway is still running, even if server have been closed.

I tested locally with `run-tests.sh` modifying.
```
# Run the tests
node --inspect ${SCRIPTDIR}/../../node_modules/.bin/jest --runInBand "$@"
```
I run tests endless.
```
while :; do ./src/test/run-tests.sh src/test/browser/ ; done;
```

When the tests not finished, I attached the debugger to the node process. I found heartbeatInterval method in `things-controller.js` were still running.

Since the Gateway have the asynchronous express middlewares, there is a possibility that the WebSocket have been closed. So, I add the code which check the websocket is opened and rerun tests endless.
`things-controller.js`
```
ThingsController.ws('/:thingId/', function(websocket, request) {
  if (websocket.readyState !== WebSocket.OPEN) {
    return;
  }
```

`new-things-controller.js`
```
NewThingsController.ws('/', function(websocket) {
  if (websocket.readyState !== WebSocket.OPEN) {
    return;
  }
```

Several hour later, tests have not been stopped.

**Comment by hobinjk** [comment]
This is great! Thanks for tracking down the root cause. Can you put those changes into a pull request?
