### ISSUE TITLE
Question: Do the Gateway have best practice to provide things status to third party service?

### ISSUE THREAD

**Issue by sogaani** [mozilla-iot/gateway#1088]
My google assistant service needs to provide thing poperty value via [report-state API](https://developers.google.com/actions/smarthome/report-state), when thing property is changed.

I think the Gateway have three pattern to report thing poperty value.
* Polling: third party service poll the things property API.
* WebSocket: third party service connect things websocket and get `onPropertyChanged` event.
* Addon: the Gateway Install the addon which connet local things websocket. When the addon get `onPropertyChanged` event call third party service API with property value.

I'm sure that `Polling` and `WebSocket` are official way to get property value. But, I think that they have some issue when they are used by third party service which provides service to many Gateways.
* Polling: waste third party service and tunnel service resource. It is difficult to scale out third party service, because third party service should manage that which server should connect which gateway. 
* WebSocket: waist third party service and tunnel service resource because third party service have to keep connection per Gateway. It is difficult to scale out third party service, because third party service should manage that which server should connect which gateway. 

I think that `Addon` pattern can resolve above issues, because watching property process is distributed per Gateway and third party service resource is used only when property is changed.
My concern is whether addon not providing device will be permitted.

Which pattern do you think reasonable?

Note: I'm not professional about web services, so there is possibility to have better solution.

**Comment by hobinjk** [comment]
I think as long as there's a log endpoint which keeps track of changes and events over time the need for supporting pushing to a remote service is lower. It would enable the remote service to poll only when it has spare resources without missing anything.

I do agree that there's a need for addons which provide functionality and don't provide devices. An addon which interfaces with a third-party service by pushing data to it would be interesting.

**Comment by benfrancis** [comment]
This does also raise an interesting question about Web of Things architecture.

Currently the way for a third party application to access our Web of Things gateway is to request access using OAuth and to use the HTTP or WebSocket API. This works well for a client-side application which is only talking to one gateway (e.g. a web app or native smartphone app to control your smart home).

In the use case described here, a centralised Google cloud service essentially wants to act as a proxy for the gateways of all users of the Google Assistant Action, so that Google's cloud service has a cache of the status of all devices on every users' home network and doesn't have to query the gateway directly to get its current state. The requirement here is more a case of synchronisation between gateways and the cloud service. The best solution we currently offer for that is for the cloud service to keep a WebSocket open with each gateway in order to stay in sync.

@sogaani has expressed a concern about the scalability of this approach, which is something someone from Samsung also mentioned to me when discussing adopting our proposed APIs for SmartThings. They also have a central cloud service which manages all the SmartThings hubs in the world, and he was concerned about having to keep a WebSocket open for every hub. The requirements of Google's approach are instead that a device (or gateway in this case) pushes its state up to the server using POST requests when something changes (i.e. the opposite direction to the Web Thing API).

I'd be interested to do some scalability testing on a cloud service like this to find out whether keeping open a WebSocket per gateway is really a problem, and whether it's actually less efficient than the gateway sending individual POST requests to the cloud.

The fact that @sogaani thinks we may need to create a custom add-on to do something which may actually be quite common (synchronise gateways with a proxy cloud service) may indicate that there's something missing from our APIs or architecture. Alternatively you might argue that Google and Samsung's attempts to centralise everything around their own cloud service is the wrong approach, and smart assistants should be able to monitor and control web things directly using their own URL on the web.

I also agree that we should allow add-ons which do other things than add adapters, e.g. "extensions" which modify the UI. But I think this particular use cases raises some questions about the Web of Things architecture.

@sogaani Can you implement a Google Assistant Action without implementing the report-state API?

**Comment by sogaani** [comment]
> I'd be interested to do some scalability testing on a cloud service like this to find out whether keeping open a WebSocket per gateway is really a problem, and whether it's actually less efficient than the gateway sending individual POST requests to the cloud.

It's great. I will be waiting for result.

Perhaps, wot member in Oracle may have opinion. They seems to use POST request pushing wot state in [this](https://github.com/w3c/wot/blob/master/plugfest/2018-prague/docs/Oracle%2Bnode-wot_Integration_concept.pdf).

> Can you implement a Google Assistant Action without implementing the report-state API?
@benfrancis No I can't. I should implement the report-state API. They requested me implementing the report-state API, because they added policies when I passed QA test.
I already implemented the report-state API with polling, and be Inquiring at Google QA team about the report-state API criteria, how long delay permitted. If they permit long delay, I will serve the Google Assistant with polling for now.

**Comment by benfrancis** [comment]
> Perhaps, wot member in Oracle may have opinion. They seems to use POST request pushing wot state in this.

The problem with this approach is that it means adding support for each proprietary cloud service (e.g. Oracle IoT cloud, Google Assistant cloud) to the gateway, rather than have cloud services call the gateway using a standard API

**Comment by abbydillon** [comment]
I am also looking for a solution where the Gateway would POST to Twilio (which in turn will send me an SMS message) when a sensor reaches a certain threshold. I also want to POST to ThingSpeak (or similar service) to log my data periodically. This is for a laboratory where we are monitoring the states of various equipment. 

- Mozilla IoT Gateway's webpage shows us current sensor states.
- Twilio pings us instantly when there is a problem (e.g., a refrigerator temperature rises above a certain threshold). 
- ThingSpeak archives, displays, and analyzes historical data.  

I'm hoping I can write an Add-On to the gateway that can POST to these services... but am still unsure if that is possible. Any ideas? 

I share this specific example to illustrate the ubiquity of this need. It seems many users would want a way to send immediate updates to an outside service if, say, a motion detector detects an intruder, a moisture sensor detects a that a hot water heater has burst, or a RFID reader notices the milk is gone from the fridge. It would seem important to allow for this in the Mozilla IoT architecture.

**Comment by benfrancis** [comment]
Currently the only type of add-ons available are adapter add-ons, which are designed to adapt an existing protocol to the Web Thing API.

Receiving notifications of certain thresholds and events is certainly a common use case, I think this is something we're going to try to add in 0.6.

With regards to logging data, rather than creating an add-on whereby the gateway POSTs data to a cloud service, another approach is to have an analytics service request access to the gateway via OAuth and either poll with HTTP or open a WebSocket to log data. See this blog post https://hacks.mozilla.org/2018/05/visualizing-your-smart-home-data-with-the-web-of-things/
