### ISSUE TITLE
Action input labels incorrectly returned

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1105]
When returning, the action labels are corrupted if they contain special characters/HTML entities. For example "My Sonos" turns into "MynbspSonos", or "Steven's Room" even turns into "Steven039snbspRoom".

This means that the schema validation will fail if any of those properties are required and thus the action can not be executed.

This is on current master, so c7409333531980613aed911541acea6bc396137c

**Comment by benfrancis** [comment]
Note that the key of actions (and properties and events) in the Thing Description is really meant to be a machine-readable ID rather than a human readable string and therefore isn't expected to contain spaces or special characters.

We're looking at adding a "name" or "label" member to property, action and event objects for use as the human readable labels, we just need to pick which term to use! (The current W3C spec is ambiguous).

See https://github.com/mozilla-iot/wot/issues/81

**Comment by freaktechnik** [comment]
I'd argue my labels are "machine readable IDs", they just happen to also be the label exposed to the end-user, fact is, that grouping seems to work via speaker name in the sonos lib I'm using.
