### ISSUE TITLE
Add-on names inconsistent between Add-ons view and Add-ons directory view

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1110]
Nit: It bugs me that when I add an add-on from the add-ons directory it has a name like "Web Thing", but once installed it shows an id like "thing-url-adapter".

I vaguely remember @mrstegeman telling me there's a technical reason for this, but it feels like broken UI. The name and ID could be completely different and the user might not recognise the add-on they just installed.

**Comment by mrstegeman** [comment]
The issue is that we added a `display_name` field to the add-ons list, which is where the friendly names are coming from. Currently, those names are not in the add-on's `package.json`, but we could start requiring that.

https://github.com/mozilla-iot/addon-list/blob/master/list.json#L254
https://github.com/mozilla-iot/thing-url-adapter/blob/master/package.json#L2
