### ISSUE TITLE
Handle device description changing

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1134]
Device's properties and actions may change, either in between adapter updates, or just because the user changed the configuration of the device.

In order for such changes to be reflected in the gateway UI, the device has to be removed and added again currently.

The gateway should update the displayed properties and actions itself.

**Comment by benfrancis** [comment]
Is this really an issue with the thing url adapter?

**Comment by mrstegeman** [comment]
No, this is definitely a gateway issue. The same issue can occur if another add-on is updated and reports a thing in a different way, such as adding new capabilities.

**Comment by benfrancis** [comment]
OK, thanks

**Comment by chris-zen** [comment]
This is specially annoying while developing WebThings, because you need to remove and re-add every time a change is done for the Thing. I am wondering if a `Refresh` option in the Thing contextual menu would be a possible solution.

<img width="157" alt="screen shot 2018-08-20 at 18 41 32" src="https://user-images.githubusercontent.com/932644/44353952-cd434900-a4a8-11e8-836a-27d316d1d646.png">

Another behaviour I have seen is that when the Websocket connection is broken (because I re-start the thing server), the Gateway doesn't update the Thing state, remaining with old values until a `propertyStatus` is sent. Maybe another possible solution would be to update the Gateway Thing every time a new Websocket connection is stablished (not sure this makes sense, just thinking loud).

**Comment by benfrancis** [comment]
> I am wondering if a Refresh option in the Thing contextual menu would be a possible solution.

Interesting idea, but I don't think it should be up to the user to manually request an update. The gateway should be able to handle this automatically.

**Comment by benfrancis** [comment]
> Maybe another possible solution would be to update the Gateway Thing every time a new Websocket connection is stablished (not sure this makes sense, just thinking loud).

See https://github.com/mozilla-iot/wot/issues/95

**Comment by personalnadir** [comment]
I'm currently seeing this in 0.8.1 using a Fibaro multisensor. 

<img width="745" alt="Screenshot 2019-07-22 at 20 09 11" src="https://user-images.githubusercontent.com/559503/61658251-e0642780-acbc-11e9-9ea9-196c47ba5b99.png">

It would be handy to be able to delete these entries somehow, as it becomes impossible to tell which the ghost devices are.

I was struggling during set up to get the device to connect. So I went through the process of adding the device. The device would appear, I would save it, but the thing would not appear and the thing's range test to the gateway would fail. So I factory reset the device and tried again.

I have cleared out the things database, but can't clear these ghosts.

**Comment by dhylands** [comment]
We don't currently have a way in the UI to remove these ghost entries.

**Comment by dhylands** [comment]
You can factory reset the dongle (which will remove all of the devices) and repair the working devices.

The zwave dongle is remembering the ghost devices and needs to be told to delete them.

**Comment by personalnadir** [comment]
@dhylands Thanks for the tip on resetting the dongle. I was trying to look through the code and figure out where they were coming from.
