### ISSUE TITLE
Checksum error while adding new add-on on windows.

### ISSUE THREAD

**Issue by apatti** [mozilla-iot/gateway#1195]
Hi,

I am trying to install example-adapter on windows gate.

Steps followed:
1. clone the example-adapter repository into $HOME/.mozilla-iot/addons directory.
2. Ran package.sh in the same folder.

Now when I try to restart the gateway, I get the following error:

2018-07-17 01:48:24.302 Checksum failed in package example-adapter: *package.json
2018-07-17 01:48:24.305 Failed to load add-on: example-adapter
Checksum failed in package example-adapter: *package.json

Can someone let me know if I am missing something?

**Comment by sogaani** [comment]
Hi @apatti 

I try your steps on windows10, however I cannot reproduce bugs.

If example-adapter has `.git` directory, the gateway does not validate checksums.
It means step 2 does not make sense, if you clone the addons into $HOME/.mozilla-iot/addons directory.

Do you have `.git` directory on `$HOME/.mozilla-iot/addons/example-adapter`?
Would you provide logs when execute package.sh?

**Comment by dhylands** [comment]
What might be happening is that somewhere along the way, the newlines in the text files may have been replaced with carriage-return newlines, which will mess up the checksums.

Creating a .git directory inside the `~/.mozilla-iot/addons/example-adapter` directory will turn off the checksum checks (as @sogaani mentioned). Running `package.sh` should recompute the SHA256SUMS file and then it should load without errors.

You could also be running into issues if you're using cygwin with text-mode mounts rather than binary mode mounts.

**Comment by apatti** [comment]
thanks for the help... I deleted the .git folder and hence was facing the
checksum errors.


Cheers,
Ashwin
