### ISSUE TITLE
Smart Assistant Hints

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1218]
As a user I want to be given hints about the types of commands the smart assistant understands so that I can try out new commands.

Given we haven't got around to implementing #950 yet, the assistant screen is currently very blank in its empty state.

I think we should add hints to tell the user what they can say.

In an ideal world these would be randomly generated commands based on a list of possible commands and the actual names of devices.

But simply adding a string like:

> Try saying things like "Turn the kitchen light on"

Would be a starting point.

**Comment by hobinjk** [comment]
I've figured out how to generate the hints, but where in the UI should they go? Should the hints just be in the message area and get hidden once the user says something? I could also cycle them through the placeholder text of the input once idle, but that seems like it could be a bit too subtle. An alternative would be to present them as messages from the assistant, having it say "Try saying things like "Turn the kitchen light on""

Just wondering what you think since hooking it up to UI is the difficult part of this.

**Comment by benfrancis** [comment]
> Should the hints just be in the message area and get hidden once the user says something?

This is what I imagined.
