### ISSUE TITLE
Allow custom-thing icon to be pre-set 

### ISSUE THREAD

**Issue by trentrand** [mozilla-iot/gateway#1311]
I believe developers who package their add-on should have the ability to include a predefined Custom Thing icon in their package.

Two implementation ideas would be:

- Dedicate a special filename that is automatically checked, and set as the default icon if it exists
- Allow developer to pre-populate the iconHref variable from their npm package file

**Comment by benfrancis** [comment]
What is your use case?

An add-on can expose multiple types of web things, which could be represented with a range of different icons. Providing a single icon may not be sufficient.

One thing we have discussed before is adding an `icons` member to the Thing Description so that a web thing can provide its own icon, like the icons member in a [W3C Web App Manifest](https://w3c.github.io/manifest/).

Note that many of the thing icons the gateway currently uses are not just static images, most of them represent current device state and are composed of multiple elements.

See also: #861
