### ISSUE TITLE
Too many update pings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1399]
Our analytics show a ~400% increase in update pings which is probably not more gateways but rather gateways pinging more often.

Did something change on the gateway or are the analytics broken? @hobinjk @mrstegeman

**Comment by jaller94** [comment]
I am running 0.5.3 and clicking "Update" set the status of the button to say "In Progress". After 15 minutes the gateway was still running 0.5.3 and offered the "Update" button again.

When are Update pings usually send by the clients?
Do you expect 0.5.x or 0.6.0 clients to send more pings since the 0.6.0 release?
Do you have a way to tell which version sends an update ping?

**Comment by benfrancis** [comment]
See also, #1345

**Comment by mrstegeman** [comment]
This was just an issue with the analytics scripts. Fixed now.
