### ISSUE TITLE
Camera Capability UI

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#1438]
As a user I want to access images or video from a camera so that I can check up on my home while I'm away.

**Comment by mrstegeman** [comment]
The properties I added to the ONVIF adapter can be seen here: https://github.com/mozilla-iot/onvif-adapter/blob/master/lib/onvif-device.js#L43

There are also motion (and other?) events in the spec, but my camera doesn't expose them, so I'm unsure what all is available.

The documentation for the library I'm using is [here](https://hawkeye64.github.io/onvif-nvt/). It's got pretty good coverage of the spec, so you should be able to get a good idea of what's available.

**Comment by drodbez** [comment]
Adding onto the camera capability...
Create custom event where RTSP h.264/h.265 video is sent to the desired chromecast. 
     -optionally add feature to do this automatically after motion or other triggered events occur.

Because most all smart TV's have chromecast built in, chromecast is already working with iot gateway and chromecast supports RTSP this _seems_ highly feasible?

Would suggest discouraging any mjpeg footage due to its extensive bandwidth.

Also, viewing RTSP footage with Mozilla stopped when NPAPI support was dropped.
Another possible solution could be something similar to this embedded?
https://stackoverflow.com/questions/2245040/how-can-i-display-an-rtsp-video-stream-in-a-web-page

I run a small security camera company, so I have a few different brand ONVIF cameras from fixed, motorized zoom, PTZ, fisheye at my disposal that I will gladly help test with.

**Comment by mrstegeman** [comment]
## Using RTSP Directly

A Javascript-based player is available from [Streamedian](https://github.com/Streamedian/html5_rtsp_player). However, in order to use that player, you have to license their [websocket server](https://streamedian.com/).

## Converting RTSP to WebRTC

WebRTC is a web standard, but not yet supported by all browsers -- notable absent is Safari, both on desktop and mobile.

In order to transcode to WebRTC, a server is needed. I have found 2 open source solutions, but both have extremely heavy dependencies:
* [Janus WebRTC Server](https://github.com/meetecho/janus-gateway)
* [WebRTC-streamer](https://github.com/mpromonet/webrtc-streamer)

I like the thought of using WebRTC, but Janus is super heavy, and I couldn't get WebRTC-streamer to work with my camera.

## Converting RTSP to MPEG-DASH

MPEG-DASH is a web standard, but not yet supported by all browsers -- notable absent is Safari, both on desktop and mobile.

This standard seems to be a bit of a mess right now. Supported codecs have been shifting, and transcoding is quite ugly, as multiple output files have to be generated. Playback support has to be added via library.

## Converting RTSP to HLS

HLS is a proprietary protocol created by Apple. However, the spec is free available as [RFC 8216](https://tools.ietf.org/html/rfc8216). HLS is natively supported in most browsers, if not natively then with a library.

Transcoding with `ffmpeg` is actually very, very light on resources. For example:
```bash
ffmpeg \
    -i "rtsp://<stream_url>" \
    -fflags flush_packets \
    -max_delay 1 \
    -an \
    -flags \
    -global_header \
    -hls_time 1 \
    -hls_list_size 3 \
    -hls_wrap 3 \
    -vcodec copy \
    -y /tmp/video.m3u8
```

```html
<!doctype html>
<html>
  <head>
    <title>HTML5 Live Streaming Test</title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    <video id="video" width="640" height="400" controls="controls"></video>
    <script>
      const url = "/video.m3u8";
      const video = document.getElementById('video');

      if (video.canPlayType('application/vnd.apple.mpegurl')) {
        video.src = url;
      } else if (Hls.isSupported()) {
        const hls = new Hls();
        hls.loadSource(url);
        hls.attachMedia(video);
      }
    </script>
  </body>
</html>
```

**Comment by mrstegeman** [comment]
If we go the HLS or MPEG-DASH route, codecs are as follows:
* Video: H.264
* Audio: AAC (preferred) or MP3

HLS allows some additional audio codecs, i.e. AC-3 and EC-3, but neither of those has wide browser support.

MPEG-DASH is "codec-agnostic", but the codecs above are still the ones with the widest support.

**Comment by benfrancis** [comment]
I think based on the above my personal preference would be for RTSP converted to MPEG-DASH over HLS, if we can get it to work well, just because it's more of an open standard.

See https://github.com/mozilla-iot/schemas/issues/25 for proposed Camera and VideoCamera capabilities.

Here is a start on a UI design:
![camera_and_video_camera_capabilities](https://user-images.githubusercontent.com/552417/48857207-3ab88b80-edb0-11e8-8e51-e7e50d114662.png)

In this case I think we might need to break from the "splat" style design pattern in order to make more room for the video/image display and not require a second click to view them. However, some open questions:
* What media controls are necessary? Will the standard `<video>` playback controls suffice for videos? Do we need a reload button for an ImageProperty?
* What happens if the Camera or VideoCamera capability are combined with another capability like MotionSensor or some kind of PTZ functionality? It may be difficult to display other properties with this design.

**Comment by benfrancis** [comment]
> What if we still have a splat, but there is a generic video stream icon that can expand into the player? That would allow for other properties to be displayed as usual.

That was actually the design I came up with first. What I didn't like with that approach was that it would require two clicks from the Things screen to get the video to play and to see any actual useful information.

We may be forced to do something like that if we want to display many other properties though...

**Comment by freaktechnik** [comment]
What if instead of replacing the splat there's an alternative view, similar to how the external view a thing can specify as alternate works?

**Comment by benfrancis** [comment]
> What if we still have a splat, but there is a generic video stream icon that can expand into the player? That would allow for other properties to be displayed as usual.

That could look something like this.

![video_camera](https://user-images.githubusercontent.com/552417/49044482-db021c00-f1c5-11e8-8cc5-2ae6959fb57d.png)

 I'm just not keen on requiring another click to get to the video...

**Comment by mrstegeman** [comment]
@benfrancis Yep, that's what I was thinking of. @freaktechnik's idea is interesting as well.

**Comment by mrstegeman** [comment]
I like it. I updated the ONVIF adapter today to match the new schemas and did some prep work in the gateway, so I should be able to start implementing this. Icons would be great.

**Comment by benfrancis** [comment]
Icons:
* [Camera capability (without circle)](https://drive.google.com/file/d/1TAfQ2Hb4zgnCmFJPIpSR1mDCbUyJ_jpo/view?usp=sharing)
* [Camera capability (with circle)](https://drive.google.com/file/d/1xrVTAuXKkVxB9hpiOVg6ZbIA5zxR27Cf/view?usp=sharing)
* [Video camera capability (without circle)](https://drive.google.com/file/d/1IZuXKnPiwdlnFh5hoL3M5yX1PMetQBxj/view?usp=sharing)
* [Video camera (with circle)](https://drive.google.com/file/d/19q0xS4twq-fRVzvdiOa89P8_oxA18F7R/view?usp=sharing)
* [Video property](https://drive.google.com/file/d/13Pg1WEREBQhM2DRNzU5JHxT6_bRLHgDa/view?usp=sharing)
* [Image property](https://drive.google.com/file/d/19FvrgKfC9wfDWk_nUOF8ttDb6tUq-DNp/view?usp=sharing)

**Comment by benfrancis** [comment]
* [reload](https://drive.google.com/file/d/1EDGO6rIEGFdqkZkcJ6tkOEmOb0Ipo9zK/view?usp=sharing)
* [close](https://drive.google.com/file/d/1kUip4qeYu9_rDuspq1Icvw30hAe69XRd/view?usp=sharing)
