### ISSUE TITLE
All adapters should be packages

### ISSUE THREAD

**Issue by KevinGrandon** [mozilla-iot/gateway#144]
As a third party developer coming into this repo I'd like to be able to create my own adapters as packages, interfacing against a well-defined API. For the initial adapters in this repo I'd recommend a mono-repo approach, either using something like lerna or file:// based packages to easily pull in adapters.

I'm leaving this intentionally vague to solicit comments and thoughts.

**Comment by benfrancis** [comment]
We had a brief discussion about this last week and I think our conclusion so far is that adapters should be node packages, with an IPC interface which uses JSON over unix sockets (very similar to the [WebSocket API](http://iot.mozilla.org/wot/#web-thing-websocket-api) but over a unix socket and using internal IDs rather than URLs for identifiers). Native binaries could be wrapped in Node packages to allow non-JS packages.

See also #169 and #170.

**Comment by benfrancis** [comment]
This is now #192
