### ISSUE TITLE
Support running gateway as a subdirectory of a web server

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#1509]
For instance, a user might want to run the gateway at https://mydomain.com/gateway.

**Comment by benfrancis** [comment]
Note that there are potential risks associated with this due to the same-origin policy. All applications served from the same origin will share the same permissions, service worker registrations, cookie jar etc. They may also share the same standalone display mode (with no URL bar) if application scope is not defined in the web app manifest or the client doesn't fully implement application scope support.

If the user is manually configuring and self-hosting then they may be OK with that, but in general it's good practice to serve each application from its own origin.
