### ISSUE TITLE
Studying the front-end code

### ISSUE THREAD

**Issue by devagrawal09** [mozilla-iot/gateway#1655]
This issue tracker might not be the best place to put this request, but I could not think of another place to put it.
I am trying to study the front-end code of the gateway. I am working on a project that involves manipulating the source code (both front and back ends) to add some extra features. The back-end should not be that difficult to comprehend, but since the front-end is not using any specific framework and there is a lack of documentation, I am having a little difficulty in fully creating a logic structure by reading all the Javascript files. If any contributor (or anyone else) who knows the front-end source well can help me figure out the whole architecture, it would save me a lot of time.

**Comment by flatsiedatsie** [comment]
I tried to 'hack' something into Mozilla Gateway too. I couldn't get it work work.

At first I just tried to change the html, but that didn't result in a new menu button.

Then I thought I had to hack a new page into the basic MVC system the gateway uses. That didn't go well as I had no idea what I was doing.

One thing I found out during all this that all the html, css and JS is zipped into one file, which (if I understand correctly) is what the browser somehow deals with.  If you do change the HTML, you have to edit it AND then start the zipping process so that you re-create the zip.

On top of that, I'm not sure if the whole Mozilla Gateway is a 'docker' project, and how that might change how you can edit things.

One thing I was now planning to try is to create a button that leads to the web interface from the login page instead, and just open that link in a new window. But I have gotten stuck too.

One thing we're perhaps both waiting for is [this issue](https://github.com/mozilla-iot/gateway/issues/1505) which is about add-ons being able to expand the interface.

It would be great if there was a simple "add an iframe as a tab in the main interface" option.

**Comment by benfrancis** [comment]
Sorry that we don't have good documentation of gateway's source code. There's an overview of the source code structure in the [README](https://github.com/mozilla-iot/gateway/blob/master/README.md) and a community member did provide this [short description](https://github.com/mozilla-iot/wiki/wiki/Gateway-Architecture), but really we could do much better. Sometimes the best people to write this kind of documentation are those new to the project who can write it as they learn, if you're up for the challenge!

@flatsiedatsie wrote:
> One thing I found out during all this that all the html, css and JS is zipped into one file, which (if I understand correctly) is what the browser somehow deals with. If you do change the HTML, you have to edit it AND then start the zipping process so that you re-create the zip.

It sounds like you might be trying to edit the source code of a production build, where all the source code has already been minified by a build process and the build system is no longer shipped with production builds in order to save space. If you want to hack on the gateway you're better off creating your own build by following the instructions in the README, for which the build will be updated every time you run npm start (or you can run it in a way which automatically detects and re-builds on changes).

**Comment by devagrawal09** [comment]
Yes I thought about going through the source code and document everything myself, but obviously it will take up a lot of time which my team is currently trying to conserve. I will definitely attempt this soon on my own time.
