### ISSUE TITLE
Integration guide

### ISSUE THREAD

**Issue by jernst** [mozilla-iot/gateway#1719]
It would be useful to have an integration guide that focuses on how to make the gateway interact with other systems (that aren't "things" or "add-on's"). It should cover topics such as:

* external user management (e.g. LDAP)
* external authorization, or integration with external authorization systems
* integration of multiple gateway instances (for larger deployments)
* integration with other web applications running on the same host
* integration with existing data storage (e.g. unified event logging)
* how to use instead, or integrate with external rules engine
* recommended development process / QA workflow / release management

Things like that ... even something fairly minimal would be useful, it can always be extended

**Comment by benfrancis** [comment]
Hi @jernst,

Thanks for the work you're doing to package the Things Gateway application for UBOS Linux.

The Project Things team's focus for this year is to evolve the current Things Gateway software into a software distribution for wireless routers based on OpenWrt, where the Things Gateway web interface would be the entire UI for the router. For this reason, requirements around running the web application alongside or integrating with other applications on a server are not our highest priority.

Having said that, I understand that some people may want to self-host the Things Gateway web application on their own DIY web server in this way and I am also personally interested in doing just that. So while I can't commit to us spending a lot of time documenting all of these things (there are other more basic things we need to better document first!), I'm sure the team and the community would be happy to help with any specific questions you have.

I'm going to close this issue, but feel free to ask questions on [Discourse](https://discourse.mozilla.org/c/iot) or in #iot on irc.mozilla.org.

**Comment by mrstegeman** [comment]
I think for now, a good option for self-hosting is to use the [Docker image](https://hub.docker.com/r/mozillaiot/gateway) we provide.

**Comment by kgiori** [comment]
In the back of my mind, I have been wondering what Web of Things properties, actions, and events the gateway should/could expose to advertise itself as a web thing. To be useful, the gateway should not be a dead end. @jernst -- what specific information sharing between the gateway and external services and applications do you think would be most useful?

And have you looked at the OAuth framework? Maybe it can be used to authorize access that is tied to an external auth system. User access could  be restricted to access/view only certain devices (monitor or monitor and control, and maybe even include an expiration date/time). 

Because the issue needs more discussion and documentation, and details on implementation concerns, a topic on the discourse channel seems like a good place to communicate.
