### ISSUE TITLE
Time Series Database

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-iot/gateway#173]
As a user I want to see a graph of my sensor data over time so that I can see trends in the data.

**Comment by benfrancis** [comment]
Example use cases:
- As a user I want to see a graph of the temperature of my home over time
- As a user I want to find out when my front door was last opened so I know whether my kids got home from school
- As a user I want to see a graph of the values from my Internet connected weather station

**Comment by hobinjk** [comment]
These are good examples of use cases, thanks!

The most important facet of a time-series database is that it is a mechanism for storing and retrieving data over time. This might sound trivial but the main thing I think is important to keep in mind is that in addition to widgets displaying simple queries of the data there's also the opportunity to do learning, prediction, and other complex operations.

**Comment by Timmeey** [comment]
Maybe we could get some inspiration from Munin and the RRDTool that they are using as their timeseries database

A very easy first approach to at least store some data, would be to build a munin plugin, which queries all sensors. this would be fairly easy, but would store and visualize the data not integrated in the gateway UI.

**Comment by rzr** [comment]
Any database backend to suggest ? should it be on device or remote ?

Is Redis adapted for this ?

**Comment by webwurst** [comment]
There is one example with using Prometheus: https://hacks.mozilla.org/2018/05/visualizing-your-smart-home-data-with-the-web-of-things/

**Comment by benfrancis** [comment]
I'd suggest an on-gateway time series should probably use SQLite like everything else, unless there's a really good reason for adding a second/switching to a different database back end.

**Comment by hongquan** [comment]
If you want a time-series database which stores data of all time, [InfluxDB](https://www.influxdata.com/time-series-platform/influxdb/) or [TimescaleDB](https://www.timescale.com) is the way to go.
RRDTool will delete the data after a duration, it cannot be used for storing all-time data.

For time-series data, you will very often query batch of the most recent data. Relational database like SQLite will be slow when you store much enough. Even if you can build index for it, you still face problem:
- If you index all points, it will cost a lot of storage.
- If you only index the N most recent data, it still be slow if you query data outside than range.

So, using a time-series DB is still better.

Now is comparison of InfluxDB and TimescaleDB:
- InfluxDB allow to summary (downsample) old data.
- InfluxDB cost much of RAM when running (maybe because it is written in Go).

**Comment by Timmeey** [comment]
Maybe we could break this task up into smaller pieces, so it's easier to comprehend what has to be done.

I could imagine this being build in 3 individual steps.
  * Build a system that enables the user to define what to do when the thing (sensor/button etc.) is updated with a new value. `gotUpdate(sensorId,oldValue,newValue,timestamp)`
  * The actual TimeSeriesDatabase, that can do nothing but receive an identifier, a value, and a timestamp
    * As a first step it could just be a stupid sqlite database that appends the given id, value and timestamp, without any time series compaction
    * second step provide ALL data as map of lists with the ID as the map Key
  * A UI system that is able to display simple x/y graphs which take exactly one method that provides a list of x(time)/y(value) tuples

From there on we could work in small bites on the problem of connecting those 3 parts together and improve them independently. But I think in such small steps its more likely to get implemented.

Especially the TimeSeriesPart is a blocker here I think, which we could mitigate by providing a simple database first

**Comment by blackfyre** [comment]
@benfrancis Since the most recommended installation platform for the Gateway is a Raspberry Pi 3, having too many file writes (like what would be the result of collecting data from multiple sensors) would make the Pi in question an SD Card cemetery...
I'd recommend a more robust implementation that could be configured to work either locally or remotely.

**Comment by mrstegeman** [comment]
Closed by #1718.
