### ISSUE TITLE
What is the minimal SoC performance requirement to run the gateway?

### ISSUE THREAD

**Issue by tonyho** [mozilla-iot/gateway#1821]
The official use the RaspberryPi as a demonstration hardware, it's 4*Cortex-A53 running at 1GHz.

Can the gateway package run on performance limitation ARM linux OpenWRT router? Like a ARM9 300MHz SoC based router, or Cortex-A7 800M Hz? 

Or the minimal SoC performance requirement ? 

I ask this question for who want to integrate this 'gateway' into the low-power routers. Hopefully, we will get the answer, thanks.

**Comment by benfrancis** [comment]
I don't think we currently have a precise answer to this question.

We do know that the Raspbian build runs quite well on the Raspberry Pi Zero W which has a 1Ghz single core CPU but only 512 MB RAM.

The in-progress OpenWrt build has a much smaller footprint, but we haven't yet tested on lots of different hardware. The first consumer router hardware we are targeting is the [Turris Omnia](https://www.turris.cz/en/turris-omnia/) which has unusually high specifications for a router.

The likelihood is that (in part due to the dependency on Node.js) WebThings Gateway will not run on the vast majority of existing router hardware. But this is partly intentional. We envisage a new breed of "smart routers" which do much more than today's limited devices, with much more capable hardware (think feature phones vs. smartphones). Perhaps capable of doing CPU/GPU intensive things like video transcoding and on-device voice recognition.

We are keeping an eye on the latest reference designs coming out of chipset vendors which have the kinds of specifications we're looking for, including built-in IoT radios.

So the short answer is that yes it will probably run fine on an 800MHz CPU, but we haven't tested that, and we don't aim to get it running on every existing consumer router. Just a few fairly high end ones.
