### ISSUE TITLE
Logs - Dynamically update min/max if necessary

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1881]
When streaming in new data the min and max of the log might need to change

**Comment by Nca78** [comment]
Hello, I think it also need to adapt to the real minimum value in the part of log we are seeing and not 0 like I seem to have for all sensors, for example here is log for a temperature sensor, graph vertical axis starts at 0°C. It's fine if graph is showing a 0-100% range like for humidity because it's easy to see the proportion, but when temperature varies between min and max of 28 and 35°C a scale starting at 0 and with no numeric value before 37°C makes it pretty hard to guess what the displayed graph really means without checking with the mouse.
If you take the example of domoticz in second picture, they have a very outdated and imho ugly design, but it's way easier and faster to analyse the displayed temperature thanks to the non-zero range minimum.
![image](https://user-images.githubusercontent.com/17949850/57925410-5f5e6d80-78d2-11e9-9c3c-1c0a0b754e9d.png)
![image](https://user-images.githubusercontent.com/17949850/57925765-8d907d00-78d3-11e9-951a-ff467845e2f0.png)

**Comment by hobinjk** [comment]
This has been fixed for a while
