### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by kawtharrr** [mozilla-iot/gateway#1945]
Hello, I've forgotten my password, what should I do?

**Comment by benfrancis** [comment]
Hi @kawtharrr, I'm afraid the forgotten password feature isn't finished yet https://github.com/mozilla-iot/gateway/issues/95

Honestly the easiest thing to do is probably just to re-flash and reclaim your subdomain (if you registered one), otherwise @mrstegeman or @hobinjk can probably craft a magic spell to remove your password from the database if you enable shell access to your Pi.

**Comment by mrstegeman** [comment]
```bash
$ sqlite3 ~/.mozilla-iot/config/db.sqlite3 "DELETE FROM users"
```

**Comment by benfrancis** [comment]
Thanks @mrstegeman!

See also: https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi
