### ISSUE TITLE
Add `id` to Thing descriptions

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#1950]
> unique identifier of the Thing (URI, e.g. custom URN).

**Comment by hobinjk** [comment]
Potentially easy way to implement this is to copy `base`

**Comment by benfrancis** [comment]
Just a note to say that I think in the Thing Descriptions our gateway exposes, the id should be the URL of the Thing Description (also the URL of its HTML representation).

**Comment by mmccool** [comment]
I don't think there is technically any reason the id can't be the URL of the TD and/or an HTML dashboard.  The definition just says that it has to be unique and a URI.  It gives a URN as an example ("e.g."), but does not require it to be a URN.   I think in the general case there are reasons and use cases where it would not be a dereferenceable URL, however.

**Comment by mmccool** [comment]
BTW I also think it would be nice to have a convention or recommendation on how to find the TD relative to "base" for introspection.   For all the test systems I have implemented I have in fact used "base" itself (I normally end my URLs in /api but since this is the same for all API entry points it belongs in the base).  The other option is to have a special rel type and use a link, but that could be a fallback for when the TD is NOT at base (eg for brownfield devices where the TD is maintained somewhere other than on the device).
