### ISSUE TITLE
Web Thing clients with Thing shadows

### ISSUE THREAD

**Issue by DurandA** [mozilla-iot/gateway#1987]
The Gateway can discover Web Things using mDNS. In this case, the content of the Web Thing from the Gateway will be polled from a Web Thing server (e.g. *webthing-arduino*).

Is there any plan for web devices acting as Web Thing clients that connect to the gateway and update their virtual entity/Thing shadow values? I know this can be achieved with a custom adapter but what is your opinion about integrating such a feature?

**Comment by benfrancis** [comment]
Hi @DurandA, the [Web Thing WebSocket API](https://iot.mozilla.org/wot/#web-thing-websocket-api) allows devices to push status updates to the gateway. The connection is still initiated by the gateway, but a socket is kept open so that the gateway doesn't have to poll it. I believe WebSocket support was recently added to the webthing-arduino library.

There are no plans for web things to act as clients which initiate a connection to the gateway, that isn't really how the [Web of Things Architecuture](https://w3c.github.io/wot-architecture/) works.

**Comment by hobinjk** [comment]
Notably webthing-arduino supports the WebSocket API on ESP8266 and ESP32 boards but doesn't yet support it using WiFi101.
