### ISSUE TITLE
SSID double entries

### ISSUE THREAD

**Issue by tim-hellhake** [mozilla-iot/gateway#2015]
I guess it lists 2.4 GHz and 5 GHz as separate entries.
![0AFF3287-E251-46E2-AA8E-E75B39A5ECAF](https://user-images.githubusercontent.com/17127122/61329026-9c84a480-a81c-11e9-85a6-1009f34d2777.png)

**Comment by mrstegeman** [comment]
Yes, they are technically separate networks. The same thing would happen if you and your neighbor were broadcasting the same SSID. I'm not sure we should deduplicate them.

**Comment by tim-hellhake** [comment]
Does it make a difference which one i choose?

**Comment by mrstegeman** [comment]
If they are both **yours**, then no.

**Comment by tim-hellhake** [comment]
Why is that? Don't you connect by SSID?

**Comment by mrstegeman** [comment]
We just write out an entry to `wpa_supplicant.conf` behind the scenes, so it's up to that process to handle connection. If both SSIDs belong to you, it will not matter which one you click on. I just don't know what the behavior would be if there were two different networks with the same SSID but different passwords.

**Comment by tim-hellhake** [comment]
Ok but then it makes no difference which ui entry i choose, the resulting conf be the same. Why not deduplicate then?

**Comment by mrstegeman** [comment]
I see your point. See #2018

**Comment by dhylands** [comment]
You can also store the BSSID in the wpa_supplicant file, which would allow you to control which of the 2 networks you connect to. You might want to only connect to the 5 GHz network, or you might want to connect to your network instead of your neighbors. Using the BSSID should probably be a separate issue, but from a security point view, this seems like a fairly important feature since otherwise someone could grab the network passwords using what's known as the "Evil Twin" attack: https://null-byte.wonderhowto.com/how-to/hack-wi-fi-stealing-wi-fi-passwords-with-evil-twin-attack-0183880/

**Comment by dhylands** [comment]
Interesting, you can buy APs already setup to do this type of thing: https://shop.hak5.org/products/wifi-pineapple

**Comment by tim-hellhake** [comment]
> otherwise someone could grab the network passwords using what's known as the "Evil Twin" attack

You can't.
It's a social engineering attack.
It's useless against a headless device like the gateway.

**Comment by tim-hellhake** [comment]
> You might want to only connect to the 5 GHz network
Usually, I want the device to decide which AP has the best signal strength.

**Comment by dhylands** [comment]
You couldn't use the evil twin attack directly, but you could setup an phony AP, and if the RPi tried to connect to the phony AP it would fail (and I think that could be forced by sending deauth?). The next question is would that make it go back into setup mode? If so then that's even easier than the social engineering.

**Comment by tim-hellhake** [comment]
> but you could setup an phony AP, and if the RPi tried to connect to the phony AP it would fail

You could do that, but that would be a DoS attack rather than an evil twin attack.

> The next question is would that make it go back into setup mode?

I think there was an issue describing this problem.
Unfortunately, I can't find it.

**Comment by dhylands** [comment]
I wasn't really concerned about the type of attack, just trying to think of ways that one might do something. We could de-duplicate the entries by including the BSSID in the list, but most users wouldn't have a clue what a BSSID is.

I just think that since we're pushing that security and privacy are important, that we should think about these things and not just makes things easier for the user (the easiest thing is no security at all). Finding the right balance is what's important.

**Comment by tim-hellhake** [comment]
The Problem with pinning the BSSID is it will break at least three things:
* Band steering
* Repeaters
* Roaming

As mesh routers become more and more popular, it would be awful for the user experience.

Even if it were possible to extract the PSK with an evil twin attack, the gateway would be just one of many devices.

**Comment by dhylands** [comment]
I don't think we'd want to pin the BSSID in all cases, perhaps just have the option to do so.
