### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#206]
If the gateway is only running on port 443/4443 then port 80/8080 should redirect. Currently you have to manually type https://

**Comment by hobinjk** [comment]
So there's the easy way to do this, which is to start a redirecting http server in startHttpsService. However, I think this is a good opportunity to clean up the logic surrounding the initialization of the http and https servers.

The way I see it there are two distinct express Routers that we want. There's the http to https redirecter, which 301 redirects unauthorized GETs and 403s everything else. Next, there's the app router which has tunnel setup, websockets, and all that jazz.

The first time setup is then the following:
- Start the app router on an http server
- When the user configures the tunnel (or skips), close the server running the app router
Now initialize the same way we'll do on any further runs:
- Verify that either notunnel or certificates exist, going to first time setup if not
- if notunnel, start the app router on http
- otherwise, start the app router on https, start the redirecter on http

The seamless switch from "close the server running the app router" to "start the app router on https" is the cause of the websocket bug.

I'm going to try to use this as an opportunity to clean up the `src/app.js` logic before it gets really convoluted (and hopefully remove the `deferredWsRoutes` hack)
