### ISSUE TITLE
[bug] all Wlan SSID being renamed to WebThings Gateway

### ISSUE THREAD

**Issue by n8v8R** [mozilla-iot/gateway#2060]
reported downstream and been deferred to report to upstream instead

https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/452

**Comment by mrstegeman** [comment]
* **Option 1:** We pull the package from other OpenWrt package feeds at this point, given that the future of the product is to include a full-fledged router UI and configuration package, and it gets absolutely zero test time outside of our full builds.
* **Option 2:** We add some workarounds so that anybody can install this, and we actually do some testing.

@benfrancis @dhylands @hobinjk What do you think?

**Comment by benfrancis** [comment]
@mrstegeman I don't think I understand what's going on here.

What package did the user install on their router and how?

**Comment by benfrancis** [comment]
See also: https://github.com/openwrt/packages/issues/9629

I didn't know anyone was still packaging new versions of our gateway software for OpenWrt downstream.

I recommend **Option 1**, as installing WebThings Gateway as an application on another router distribution is not a configuration I expect to work in future. There are likely to be many conflicts like this.

**Comment by mrstegeman** [comment]
That was my thought as well. Who do we need to talk to in order to get that package removed from the feed? @dhylands @kgiori do you know?

**Comment by BKPepe** [comment]
Just create PR in openwrt/packages, where you will remove the package and it is necessary to say the reason, why you want to get it removed.
