### ISSUE TITLE
[OpenWrt] Software image for Banana Pi BPI-R2

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#2149]
Investigate supporting the [Banana Pi BPI-R2](http://www.banana-pi.org/r2.html) as more affordable developer hardware

**Comment by flatsiedatsie** [comment]
Is this happening? If so, then I will order this hardware.

**Comment by flatsiedatsie** [comment]
Any advice?

**Comment by mrstegeman** [comment]
@dhylands is evaluating the hardware and build process to see if it will be a good fit.

**Comment by flatsiedatsie** [comment]
@dhylands Any success? I would like to use the router-version of the Gateway for an exhibit at the Dutch Design Week. There the public WiFi will be swamped with thousands of devices, so I would prefer to use the gateway as a prepared standalone hotspot that will "just work". The window to order the Banana Pi in time is closing fast.

A side-question: any indication if Bluetooth would work on this device?

**Comment by dhylands** [comment]
I've gotten a build, but the gateway software doesn't run properly because none of the Banana Pi wifi stuff is integrated into openwrt. For example, reloading the network fails, starting dnsmasq fails, starting hostapd fails, you can't configure network paramters for wifi. I think that's currently the biggest stumbling block and it's non-trivial to fix.

**Comment by flatsiedatsie** [comment]
Thanks. I'll go for the expensive router then.

**Comment by mrstegeman** [comment]
Closing. This hardware seems like a bad target for us.
