### ISSUE TITLE
Thing Sharing Across Addons

### ISSUE THREAD

**Issue by damooooooooooh** [mozilla-iot/gateway#2393]
I want to build an addon that does not generate its own things, rather it uses existing things to provide functionality. 

Example: I would like to create a Smart Thermostat controller addon that uses existing things generated from other addons (i.e. zigbee thermostat thing) to extract key data such as current temperature, heat mode etc.  The add-on functionality would consume the thing data in order to calculate the thermal dynamics of the building and to provide features like the nest Time-To-Temperature.

Is it currently possible to reference properties of other things?

**Comment by flatsiedatsie** [comment]
@damooooooooooh What you describe sounds exactly like the example I mentioned in [this post](https://github.com/mozilla-iot/gateway/issues/1840#issuecomment-490514800). I've also explored this exact example [here](https://github.com/999LV/SmartVirtualThermostat/issues/25), as the Smart Virtual Thermostat plugin for Domoticz is another example of this. As I understand it (it's been a while since I used it), it allows users to:
- Manage multiple rooms
- Each room can have a heater.
- Each heater can respond to multiple temperature sensors (which are averaged).
- For each room the plugin learns how quickly the temperature drops over time (how well insulated it is), and uses that to optimally heat it using a PID algorithm to keep the temperature as stable as possible.

One easy solution to get this working would be if add-ons get a passcode for the API when they are installed, as [proposed here](https://github.com/mozilla-iot/gateway/issues/2249). I'm really hoping that will be in the next version, as it will avoid users having to manually copy API codes into plugin settings.

Currently there's also the option for an add-on to find out which devices the user has added to their system through an add-on method called `handle_device_saved`. It actually gives your addon a list of all accepted things too. The limitation here is that it only does this at boot/when the add-on is installed, or when a thing it manages is accepted. I could imagine that if this method was expanded to provide fresh data when any new thing is added to the system, and also when thing details change, then this could also be a great way of getting data to add-ons without needing to use the API. In that case an add-on like Voco could use it to know when thing names change, for example, so it can retrain the voice recognition for all devices. Currently Voco polls the API every 20 seconds to check for changes. I'd much prefer a push-system where the gateway pushes updates.

This probably also related to the issue of permissions, as having all users/add-ons have access to all devices all the time could create some social tensions.

**Comment by damooooooooooh** [comment]
Hi @flatsiedatsie I'm just about to publish a Smart Alarm which rolls all of the functions of an alarm system into an adapter using the API access framework as suggested by @mrstegeman.  However this approach needs refinement as I've observed a maintenance issue whereby if new security type things you want to expose to the adapter are added to the system which should be consumed by the adapter then a new token needs to be created and reprovisioned back to the adapter settings.  

What would be nice is the possibility to modify the grants of an existing authorization token to increase the scope of access.  I'm not sure if there is a cleaner way to do this through the IPC but allowing adapters to talk to any component could present a security challenge, data exfiltration etc.  Maybe a adapter specific thing/grants page?

**Comment by flatsiedatsie** [comment]
> What would be nice is the possibility to modify the grants of an existing authorization token to increase the scope of access.

That's interesting. Are you sure? I was under the impression that if you select "allow access to all" when you generate an API security code, then the add-on will also have access to things added in the future. As far as I can tell it works that way with Voco. I can't remember ever running into Voco not being able to control newly added things.

Reading your post a bit better, perhaps this only happens with the security type. But I'm not sure what you mean by that. Things with a password on them?
