### ISSUE TITLE
The tunnel setup page is not being displayed in the first time setup anymore

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#242]

**Comment by dhylands** [comment]
It seems if I hit Refresh then it will show the tunnel setup page

**Comment by andrenatal** [comment]
Seems the issue is related with the the client side authentication api that redirects to the signup page if there's no user created, while the tunnel setup page is part of the express middleware.

**Comment by benfrancis** [comment]
Ah, I think I broke this with the front end/back end split.

What's supposed to happen is that the router, in order:
- Checks for a static file that matches the requested URL (e.g. a CSS or image file), if so serve it directly
- Checks whether the request accepts HTML, if so:
  - If the tunnel needs setting up, send tunnel_setup.html
  - Otherwise send index.html and delegate to the client side router
  - If the user isn't logged in then redirect to login or signup (if no user is configured)
- Checks whether the request accepts JSON, if so handle as an API request

What I think is happening is that because index.html is in static/ the first step is directly serving index.html from the static folder without going through the root controller and therefore bypassing the tunnel setup middleware and skipping directly to the client side auth step which redirects to the signup page

We need to give the tunnel setup middleware a chance to respond before index.html is sent. One solution is to move index.html out of static into views/, but this is getting a bit messy with some HTML in static/ and some HTML in views/

**Comment by benfrancis** [comment]
P.S. We should have a test to make sure this doesn't regress again!

**Comment by benfrancis** [comment]
For example, simply moving index.html from static/ to views/ would fix this bug https://github.com/mozilla-iot/gateway/pull/245

But now we have login/ and signup/ in static/ and tunnel_setup.html and index.html in views/

Any other suggestions?

**Comment by hobinjk** [comment]
I think moving `login/` and `signup/` into `views` for consistency would be the best approach, with `views` being the designated area to put HTML views regardless of whether they're static.

**Comment by benfrancis** [comment]
> I think moving login/ and signup/ into views for consistency would be the best approach, with views being the designated area to put HTML views regardless of whether they're static.

Yeah it was actually laid out that way at one point (see https://github.com/mozilla-iot/gateway/tree/65c33d8a78844b0210fbbbf779209b394ce02a1b).

I think the logic of moving them back into static/ was to try and keep the front end web app logic separate from the back end API server when the server side logic moved into src/. Currently tunnel_setup.html is the only HTML file in src/.

So yes we should probably either move all HTML files into src/views/ or put them all in static/ and use client side logic to determine whether to show the tunnel setup.

Do we think we're likely to use any server side rendering of HTML in future? If so we should probably pick src/views/, otherwise pick static/.

FWIW having a combination of both server side rendering and client side rendering is the current recommendation Google makes for Progressive Web Apps in most cases, so that they can get to first render quickly, work offline and still be crawlable by search engines.

**Comment by andrenatal** [comment]
@benfrancis I think you have a clearer vision about how the files should be laid out than me, so do you mind taking this one, please?

**Comment by benfrancis** [comment]
I suggest landing #245 to fix the first time setup as that's pretty fundamental, then figure out what to do with cases like login, signup and tunnel setup when it comes to client side vs. server side routing.

**Comment by andrenatal** [comment]
@benfrancis cool, just merged it!
