### ISSUE TITLE
About hardware compatibility

### ISSUE THREAD

**Issue by yuedizhibo** [mozilla-iot/gateway#2455]
I can't to let it to connect the mi home lamp 1s,The mi home lamp support the WIFI and Bluetooth,But I can't find it on the raspi3B+

**Comment by mrstegeman** [comment]
It looks like this light is HomeKit compatible. Try installing the HomeKit add-on. Then, search for devices as usual. If it find the device, it will prompt you for a PIN. This is usually on a sticker on the device, or in the manual somewhere, and is of the form XXX-YY-ZZZ.

I'm going to close this issue since it's not really a bug in the gateway, but feel free to continue the conversation.
