### ISSUE TITLE
Subdomain names can't be reused??

### ISSUE THREAD

**Issue by disquisitioner** [mozilla-iot/gateway#347]
I  downloaded the new 0.2.1 image to install and upgrade my existing 0.2.0 gateway.  The start-up screen wants me to specify a subdomain to use and it appears I can't (re)use the subdomain I had been using previously as an error message appeared saying the certificates couldn't be generated.  I had to make up a new subdomain name to use.    How can I reuse the original subdomain name across gateway updates and reinstalls?

**Comment by benfrancis** [comment]
You can't, yet. We collect your email address so that in future you will be able to but we haven't implemented the service to handle reclaiming subdomains yet. This will be made slightly better by the fact that we now have an OTA update system so you don't have to re-flash on every release and start again, but reclaiming subdomains is something we're still working on. We need to set up an email system so that we can email the associated email address with a unique URL to confirm authenticity, so that people can't claim each others domains!

**Comment by mrstegeman** [comment]
Superseded by #379
