### ISSUE TITLE
Unpairing Devices

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#350]
As a user, I want to unpair devices associated with the gateway

**Comment by mrstegeman** [comment]
Is it sufficient to just properly unpair when a device is removed from the UI?

**Comment by benfrancis** [comment]
Is that actually possible with all protocols though? I seem to recall some devices require you to press a hardware button on the device itself to un-pair it, but I might be wrong.

We currently have two separate stages in the UI for "discover/pair" and "save". Tapping the "+" button puts the radios in pairing mode (and in future will also listen for broadcasts on the local network). Once devices are paired or their broadcast is detected they appear in the add things screen. You can then click "Save" to save the thing to the things database. This allows the user to see the devices which are available on the network, before saving them to the gateway.

When you remove a Thing it currently removes it from the things database but it doesn't un-pair it. If it could un-pair it as well that might make sense, although what about devices that appear in the add device screen but aren't yet saved? You'd have to save them to the gateway first in order to un-pair them.

One option is to have a remove button on each device in the add thing screen so you can un-pair devices you didn't mean to pair or no longer want. But then unpairing a device from the things screen starts with clicking the "+" button which is counter-intuitive. Also not all devices can be un-paired,

We need to take into account various different protocols. ZigBee, Z-Wave and WPS are fairly similar but Bluetooth pairing works a bit differently and not all protocols have a pairing and un-pairing mechanism.

Are there any use cases for removing a device but not unpairing it? Currently I do that to re-name things but that's only because we don't have a rename function!

**Comment by mrstegeman** [comment]
This is all complicated by the fact that the discovery and pairing process is different for everything. For instance, with HomeKit, you can't get any useful information out of a device until you actually pair with it. So to make that work, the adapter is currently pairing with any devices that it either has saved pairing data for, or a PIN configured.

In cases like this, it actually would be useful to be able to unpair devices you didn't actually save. I think the problem is that the adapters don't actually know which devices the user has saved. It just knows what devices it has found.

For devices where there is no actual pairing process, such as TP-Link, none of this matters.

**Comment by mrstegeman** [comment]
I think a decent option would be to allow for pairing during the discovery process, but then send the adapters a notification when a device is actually saved, such that they can later (periodically, or before shutdown) unpair with anything that is not actually saved. Also, I see no reason why unpairing shouldn't happen as part of removing the device.
