### ISSUE TITLE
Automatic certificate renewal

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#378]
As a user I want certificates for my subdomain to be renewed automatically on my behalf so that I don't have to renew them manually

**Comment by mrstegeman** [comment]
#364 added automatic renewal for newly created domains on the gateway.

If this issue is intended to cover more cases than that, i.e. existing certs, we will need to do some additional work. Previously, the renewal config file was not being written to the file system, so the new renewal systemd service will not renew existing certificates.
