### ISSUE TITLE
Add UI to allow users to configure an add-on

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#421]
As a user I want to configure my add-on from the main UI

**Comment by dhylands** [comment]
It turns out that you can disable the blinking LED on the Aoetec ZStick, This [page](https://aeotec.freshdesk.com/support/solutions/articles/6000171881-how-to-disable-led-on-z-stick-gen5-) mentions that domoticz (an open-source home automation system) can do it. This would be an example of an adapter-specific configuration.

**Comment by sogaani** [comment]
My broadlink adapter needs a UI to learn ir code.
In order to show the process of learning to the user, I need interaction between UI and adapter.

If this issue is not under development, I would like to develop some functions of this issue.
I am considering the following functions.
- Provide Controller class like add router to add-on.
- Addon can respond to access(get put post delete....) of /:addonName/controller/** by registering controller in addon-manager.
- Provide as part of the API request and response API (render send status ....) as a proxy for addons in plugin mode.

Can I try it?

**Comment by benfrancis** [comment]
This is a good example of an add-on which may need its own configuration UI.

I'm a little bit hesitant to let add-ons extend the gateway's public Internet-facing REST API. Is there another way this could be achieved? Perhaps a mechanism to let add-ons declaratively define configuration parameters which should be displayed for the add-on, by the gateway UI?

Can you provide a bit more information about the configuration needed? Could this be achieved by a set of configuration parameters represented as form elements, or does it require a completely custom UI? Note that there's currently no way for add-ons to define their own UI, but we have discussed the idea of "extension" add-ons which can extend them gateway UI.

**Comment by mrstegeman** [comment]
@benfrancis The GPIO and HomeKit adapters (and possibly the Hue) adapter could really use a configuration UI as well.

What if the add-ons could provide a list of parameters with a type, i.e. String, Number, Array, Object, etc., along with current values, and we render some basic form?

**Comment by benfrancis** [comment]
> What if the add-ons could provide a list of parameters with a type, i.e. String, Number, Array, Object, etc., along with current values, and we render some basic form?

That sounds good to me.

**Comment by sogaani** [comment]
@benfrancis I think so about the public REST API.
I think the idea of @mrstegeman is good.
Most addon developer will not want to make UI themselves.

But in my case it is necessary to interact to learn the broadlink device and IR code.
If actions api is implemented, interact to learn IR code are possible, but in the idea of @mrstegeman it seems difficult to set the response of actions api.
I am glad that there are options that allow to specify mustache or html file.

**Comment by dhylands** [comment]
Another way of thinking about this would be to have a configuration thing which could then have properties and actions.

**Comment by benfrancis** [comment]
> Another way of thinking about this would be to have a configuration thing which could then have properties and actions.

That sounds confusing to me.

There's already a configure button in the add-ons UI mockups. We just need to figure out the screen that comes up when you click the button. I agree it may be a similar concept to Thing properties where an adapter can have a set of declaratively defined configuration fields which we render form input elements for in the UI, but I think that should be in settings, not represented as a Thing. It actually sounds a bit like prefs in Firefox.

**Comment by benfrancis** [comment]
(and in fact similar to the settings we already store in the gateway database, but per add-on).

Some more detailed use cases might help. What does "show the process of learning to the user" actually involve?

**Comment by sogaani** [comment]
The number of IR codes get for each IR device (air conditioner, light, switch) is different. For example, switch require on/off, but in dumplingLight additionally levelUp levelDown is also required.

For this reason, in the first step, the user selects which type of device to add and enters [some parameters](https://github.com/sogaani/broadlink-adapter/tree/master/example).

The second step is to get IR codes for the operation of the selected IR device. This process is repeated as many times as necessary IR codes.
For lights and switches, the number of times get IR codes is fixed.
However, since the air conditioner needs to get IR codes for each set temperature, the number of times will vary depending on the maximum temperature and the minimum temperature.

The flow of get an IR code is as follows.
- Addon switches broadlink to learning mode
- Notify the user that the add-on has switched to learning mode
- The user points the IR remote control toward broadlink and presses the button.
- IR code of button with broadlink pressed is sent to add-on.

**Comment by mrstegeman** [comment]
So far, the configurations required by our add-ons are the following:

* BroadLink:

    ```
    "config": {
      "devices": [
        {
            "mac": "34:ea:34:c7:b2:ec",
            "type": "dimbleLight",
            "id": "dimbleLight01",
            "name": "Living dimbleLight",
            "ir": {
                "on": "26005000000124911311141114111411141114111411143513111435133513351311143513351311143513111411141114351311141114111411143513351335131114351335133513000d05",
                "off": "26005000000124911311141114111411141114111411143513111435133513351311143513351311141114111411141114111411141114111435133513351335133513351335133513000d05",
                "levelUp": "26005000000124911311141114111411141114111411143513111435133513351311143513351311143513111435131114111411141114111411143513111435133513351335133513000d05",
                "levelDown": "26005000000124911311141114111411141114111411143513111435133513351311143513351311141114351335131114111411141114111435131114111435133513351335133513000d05"
            },
            "onLevel": 100,
            "levelStep": 5
        },
        ...
      ]
    }
    ```

* ESP

    ```
    "config": {
      "ipStart": "10.0.2.10",
      "ipEnd": "10.0.2.20"
    }
    ```

* GPIO

    ```
    "config": {
      "18": {
        "name": "led",
        "direction": "out",
        "value": 0
      },
      ...
    }
    ```

* HomeKit

    ```
    "config": {
      "pinCodes": {
        "device-id-1": "pin-code-1",
         ...
      }
    }
    ```

* http-on-off

    ```
    "config": {
      "url": "http://wifi101.local"
    }
    ```

* Serial

    ```
    "config": {
      "ports": {
        "arduino-usb": {
          "manufacturer": "Arduino"
        },
        ...
      }
    }
    ```

* Zigbee

    ```
    "config": {
      "scanChannels": "0x1ffe",
      "discoverAttributes": false
    }
    ```

**Comment by guymcswain** [comment]
Some of the examples above seem to be "configure my thing" requirements as apposed to "configure my add-on".  My example would be my zwave motion/light detector thing that has parameters for alert timeout, light threshold, etc.

I tend to prefer @benfrancis suggestion:

> Perhaps a mechanism to let add-ons declaratively define configuration parameters which should be displayed for the add-on, by the gateway UI?

... but for thing parameters.

**Comment by mrstegeman** [comment]
@guymcswain We don't currently have any type of per-device config, but what you're suggesting could also be done at the add-on config level. For instance, the config could contain a set of device-specific parameters with a Z-Wave identifier or something that would be applied when paired.

**Comment by mrstegeman** [comment]
@sogaani Has been working on a nice patch set for add-on configuration here: #751

**Comment by dhylands** [comment]
In the case of ZWave, most of the configurable parameters are actually advertised by the device itself. We just need to expose them.

**Comment by guymcswain** [comment]
That's good to know.  Any timeframe for this to be released?

And now I see your point about the LED on the USB stick being add-on specific.
