### ISSUE TITLE
Network Settings

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#423]
As a user I want to configure my network settings so that I change the network my gateway is connected to

**Comment by benfrancis** [comment]
WIP UI mockups:
![network_settings](https://user-images.githubusercontent.com/552417/40852363-2285b36a-65c2-11e8-8cfc-17ae06afd968.png)

Having started designing this, I've realised what a huge task this is going to be. Firstly, configuring WiFi from the gateway web interface may require merging the first time setup WiFi server with the main gateway server, otherwise we're just duplicating code.

Secondly, there's a lot that can go wrong here, like getting a WiFi password wrong leaving the gateway in a broken state, or accidentally disabling all the network interfaces! There may be some limitations of the Raspberry Pi we have to work around (like not being able to act as a WiFi hotspot while simultaneously connecting to another WiFi network). It also occurs to me that this UI might look quite different if the gateway web interface is the UI for a router.

I'm wondering how much of this we want to get into 0.5. What are the main use cases that we have at the moment? It seems like a key use case is changing the WiFi network a gateway connects to when moving the gateway to another location (e.g. for a conference), but building a UI for that isn't very useful if you can't connect to the gateway in the first place.

What is the current behaviour when the gateway fails to connect to a WiFi network? Does the WiFi first time setup web server and hotspot start up? If so, I'm not sure this would be adding much.

**Comment by kgiori** [comment]
The Wi-Fi setup does indeed revert to broadcasting the "Mozilla IoT Gateway" SSID and acting as a hotspot if the RPi fails to connect to the configured SSID of an AP. It does that if it can't connect via Wi-Fi after a reboot. I don't know if there is a timeout such that it reverts to acting as an AP without a power cycle. If the rest of the setup has already been completed, then exposing the scanned and visible SSIDs is a good approach for the client that connects to "Mozilla IoT Gateway". I also like having a page to configure the "Wi-Fi Hotspot" SSID to something else, so that I can identify my gateway from someone else's, in case mine loses its connection. One option for the configuration page in addition to chaning the captive portal SSID that I would like to see is the option of adding a password (i.e., locking down the SSID of the hotspot so that someone else can't change the config if you are not around to fix it.) On the Ethernet config page, the only option I think we might want to expose is allowing the user to change from DHCP to a static IP address, with netmask and gateway IP addr.

**Comment by kgiori** [comment]
The other thing I'd like to see on the "Network" config page is a "ping" button. It would test a ping to the internet, such as to mozilla.org. Or an advanced feature would be to have a blank field next to the ping button that would let the user type an IP address or a domain name that they want to try to ping. If the space is left blank, we'll try a domain of our choice.

**Comment by dhylands** [comment]
Currently, if the gateway can't get wifi and isn't configured to skip, then it will go into AP mode.

Configuring most devices (like IP cameras) have all of the same issues when trying to configure (i.e. entering an incorrect password will mess things up). I don't think we should allow disabling the ethernet connection. If you want it disabled, unplug the cable.

Things we need to be able to configure for either wifi or ethernet:
1 - Have one of 3 modes, DHCP, Static, and DHCP for IP address only (allows you to configure DNS manually but get IP address via DHCP).
2 - For static, we need to be able to set IP address, netmask, and gateway (IP address of network gateway not our gateway)
3 - For static and IP-only via DHCP we need to be able to set DNS server addresses

**Comment by benfrancis** [comment]
Given I think the no. 1 use case is already met, I'm going to punt this to the next release.

**Comment by kgiori** [comment]
For Raspberry Pi or other Mozilla Things Gateway hardware that is normally configured in "Wi-Fi client mode", a possible enhancement would be to enable the user to list multiple Wi-Fi AP credentials, in order of priority. Then if a user is moving the gateway from one network (e.g., work), to another (e.g., home, conference venue, cellular hot spot), they can enter the alternate credentials into the WI-Fi Network GUI. The RPi would try to connect to the first AP's creds on the priority list, and if that fails after some timeout, proceed to try the next, and the next, before reverting to become an AP with ssid "Mozilla IoT Gateway". it might also be nice to be able to tell the Things Gateway to switch to a different AP network (or even a different band on the same AP). Ideally this would be done by having the RPi re-scan the Wi-Fi airwaves and show a list of possible APs to connect to, similar to the initial Wi-Fi setup, except that it will already be a client mode device, not an AP.

Another thing I'd like to see on a network configuration page is simply status of the config. 
* IP address, netmask, gateway IP, and interface name (for each active interface)

**Comment by kgiori** [comment]
Rather than tackle the full network configuration complexity at once, we could start with only a "Wi-Fi" (re)configuration option, within Network Settings. The option could display a "Scan" button that when clicked, would bring up a new page showing results of an AP scan, much like initial setup. If the user clicks on a different ssid, the UI would ask for the password and then attempt to switch to the new network. If it failed, it would be nice if it could fall back to the previously working AP.

**Comment by kgiori** [comment]
I also like how the initial "Network" UI shows the IP address of Ethernet and Wi-Fi. Another "start simple" option for this feature is to just display status of Ethernet and Wi-Fi by listing the IP address of each, and by showing the ssid for the Wi-Fi. We can postpone Wi-Fi (re)scan, config, and disable/enable to a later release.

**Comment by benfrancis** [comment]
OK, here are my initial ideas on some basic network settings which can work in both client and router modes.

![network_settings2](https://user-images.githubusercontent.com/552417/52437464-e13e3e00-2b0e-11e9-8d02-0124df02c150.png)

This is not intended to be in any way exhaustive, just the absolute basics we need to configure the gateway as a client, a wireless access point or a wireless router. We can add additional fields like netmask, DNS servers, DHCP IP range, DHCP leases, WiFi channels etc. later if needed.

As a stop gap for the OpenWrt build we will likely also need an "Advanced Router Settings" section in settings which just links to Luci for more advanced configuration.

I have intentionally used terms like "Internet" and "Home Network" rather than "WAN" and "LAN" on the assumption that most non-technical users won't know the difference between a WAN and LAN. I've also used a liberal sprinkling of little help icons for in-UI help in the form of tooltips which we can define.

Wi-Fi Settings has three modes:
- Wi-Fi Access Point
- Client
- Disabled

Home Network has two modes:
- Router
- Client

Internet (WAN) has two modes:
- Automatic (DHCP)
- Manual (Static IP)

I'm not sure how useful that last section really is at this point. If you have a WAN port, you're probably going to use DHCP, and if you don't then you won't care.

What do you think?

**Comment by mrstegeman** [comment]
1. We should probably cover PPPoE for WAN mode.
2. Would it be a huge stretch to include DNS settings?
3. I'm confused about the difference between the client mode of "Home Network" and "Wi-Fi Settings".

**Comment by dhylands** [comment]
The initial setup screen says "Connect to existing Wifi newtork" and "Create Wifi network", but then these screens use different terms like "Client" and "Router". We should use the same temrinology everywhere to make this less confusing.

**Comment by dhylands** [comment]
And it occurred to me that another mode is "Extender" where the Wifi is used to connect to an existing network and the LAN ports then behave like they're plugged into the "Main AP". 

Here are the 3 different ways I see of using the gateway:
https://photos.app.goo.gl/8PWFHY47Yk3ynddm8

**Comment by benfrancis** [comment]
@mrstegeman wrote:
> We should probably cover PPPoE for WAN mode.

OK. I think we may be able to get away without this for a first pass, but I've added a mockup in case it's a straightforward addition.

> Would it be a huge stretch to include DNS settings?

Not a huge stretch, no. But let's maybe discuss that in a [separate issue](https://github.com/mozilla-iot/gateway/issues/1648). You might also want to set other things like the default gateway and network mask but I'm trying to keep this to the bare minimum to start with.

>   I'm confused about the difference between the client mode of "Home Network" and "Wi-Fi Settings".

The difference is basically that one is WiFi and the other is Ethernet. It is a bit confusing to have a client option for each, but they are really separate things.

@dhylands wrote:
> The initial setup screen says "Connect to existing Wifi newtork" and "Create Wifi network", but then these screens use different terms like "Client" and "Router". We should use the same temrinology everywhere to make this less confusing.

Usually I would agree on the consistency point, but in this case I'm aiming fora first time setup experience that anyone can use without knowing all the technical terms like LAN, WAN and DHCP - but then Network Settings which are flexible enough for power users to configure the network exactly how they want.

> And it occurred to me that another mode is "Extender" where the Wifi is used to connect to an existing network and the LAN ports then behave like they're plugged into the "Main AP".

All three of those modes should be possible to configure in Network Settings. For first time setup I'm trying to keep the number of options as small as possible to cater for the simple configurations that will be used 90% of the time.

![network_settings3](https://user-images.githubusercontent.com/552417/52727898-1d115180-2fae-11e9-8f34-8b4f84ec2dc6.png)

**Comment by kgiori** [comment]
Typical Wi-Fi router hardware: WAN, LAN, and WLAN, where LAN and WLAN are bridged by default. Most Wi-Fi routers have one WAN port, multiple LAN ports (typ 4), and minimally a 2.4GHz radio but in many cases also a 5GHz radio. An RPi is not a traditional Wi-Fi router platform. These settings look like they were written with an RPi in mind, not just a Wi-Fi router. If we can detect non-traditional hardware like the RPi, then hopefully we can automatically change these settings pages to match what ports are available. But as a starting point I would assume router hardware.

On the main "Network" page at the top, **above** "Internet" (WAN), "Home Network" (LAN) and "Wi-Fi" (WLAN), I would add "Network Mode", with a configuration button that opens a settings page to allow selecting one of three modes. The "status" area below the term "Network Mode" would show which option has been configured.

These are the options I would expose, assuming typical router hardware.
MODES:
1. Wi-Fi Router (WAN separate from DHCP server for LAN/WLAN)
2. Wi-Fi Access Point (WAN bridged to LAN/WLAN)
3. Wi-Fi Client (WLAN typically bridged to LAN; WAN port either disabled, set to static IP address, or added to the bridge; I prefer WAN set to static IP address for back door config if needed)

Then pages for the three columns for Wi-Fi (WLAN), Home Network (LAN), and Internet (WAN) should show the type of mode that has been configured, but not allow the mode to be changed from those pages. (Because if you change the mode in one of them it potentially affects them all.)

WLAN
For the "Wi-Fi" config pages, for top row screen I would change "SSID" to "Network Name (SSID)". That screen would be applicable for both router and AP modes. That page should also have a "Disable Wi-Fi" check box since the bottom Wi-Fi page in that column is no longer applicable. It would also be nice to see a list of connected wireless clients below the configuration section of the page. 

The middle row showing the Wi-Fi client config page is fine (except there won't be a mode selection on it). I would also show the IPv4 address after the status "Connected" if possible.

LAN
For the "Home Network" column, if config is "router" mode, the top row screen would show an editable "Static IPv4 address" field (but no mode nor "DHCP Server" checkbox.) Below the config settings, it would be nice to see a list of DHCP-connected clients and their IP addresses (and "lease time remaining" as a bonus.)

If the mode is AP or client, then the Home Network page could show the IP address that was received by the WAN (AP mode) or WLAN (client mode), since it would be bridged to that same IP, but it would just be status data since there would be nothing to configure.

WAN
For the "Internet" column, instead of "mode", the configuration drop-down option label could be something like "Internet (WAN) connection type". It would be nice to see connection status on this page, for any of the three options. If automatic DHCP, show the IP address received from the upstream router. If static (e.g., entered as 192.168.1.42), we either need to assume a subnet mask of 255.255.255.0 and upstream router with same subnet as manually entered IP address except ending in .1 (e.g., 192.168.1.1), or we should show those two additional editable fields (and  automatically fill them in with defaults just described.) If PPPoE, again simply show status of the connection below the configuration fields.

Back to the "top" light blue screen, as much status information as possible on that page would be nice. For example:
* Network Mode - show current mode
* Internet - show "Connected - DHCP - actual IPv4 addr" or "Connected - Static IP - actual IPv4 addr" or "Connected - PPPoE - username?". Alternatively, status could be "Not Connected - [show config'd option]" - which shows the config option but no dynamic data since there's no upstream connection.
* Home Network - show IPv4 addr and number of connected clients if applicable
* Wi-Fi - show SSID being broadcast or the upstream AP being connected to and status of that connection.

**Comment by benfrancis** [comment]
> These settings look like they were written with an RPi in mind, not just a Wi-Fi router.  If we can detect non-traditional hardware like the RPi, then hopefully we can automatically change these settings pages to match what ports are available. But as a starting point I would assume router hardware.

That's correct. It's designed such that the same Network Settings UI could be used whether the user chose the client or router option during first time setup.

I'm not sure detecting the hardware will necessarily help given that you could configure a Raspberry Pi as a router, using the Ethernet port as a WAN port and the WiFi as a WiFi access point. It depends more on how the user configured the gateway during first time setup.

Ideally I'd like to just remove the client options because you wouldn't configure a router that way, but that's probably going to cause problems for our existing user base.

Another option could be that we have a different first time setup and a different set of settings for the Raspbian version and the OpenWrt version, but that might get complicated.

> 
> On the main "Network" page at the top, **above** "Internet" (WAN), "Home Network" (LAN) and "Wi-Fi" (WLAN), I would add "Network Mode", with a configuration button that opens a settings page to allow selecting one of three modes. The "status" area below the term "Network Mode" would show which option has been configured.
> 
> These are the options I would expose, assuming typical router hardware.
> MODES:
> 1. Wi-Fi Router (WAN separate from DHCP server for LAN/WLAN)
> 2. Wi-Fi Access Point (WAN bridged to LAN/WLAN)
> 3. Wi-Fi Client (WLAN typically bridged to LAN; WAN port either disabled, set to static IP address, or added to the bridge; I prefer WAN set to static IP address for back door config if needed)
> 
> Then pages for the three columns for Wi-Fi (WLAN), Home Network (LAN), and Internet (WAN) should show the type of mode that has been configured, but not allow the mode to be changed from those pages. (Because if you change the mode in one of them it potentially affects them all.)

OK, so you're suggesting the top level sections in Network Settings would be:
- Network Mode
- Internet
- Home Network
- Wi-Fi

That would be quite a confusing information hierarchy because choosing a mode from the "Network Mode" section would need to change settings in the other three sections, and changing a setting in one of other three sections could effectively put the router in a different network mode. The network modes you list are really aggregations of a bunch of settings from the other three sections.

> WLAN
> For the "Wi-Fi" config pages, for top row screen I would change "SSID" to "Network Name (SSID)". 

Done.

> That screen would be applicable for both router and AP modes. That page should also have a "Disable Wi-Fi" check box since the bottom Wi-Fi page in that column is no longer applicable.

We still need to have the client option because that's the only wireless mode our current user base is using (unless we have a different version of settings for the Raspbian and OpenWrt distributions, as described above). Therefore it makes sense to have "Wi-Fi Access Point", "Client" and "Disabled" as options.

> It would also be nice to see a list of connected wireless clients below the configuration section of the page.

My plan is that this list of devices would eventually be part of the things screen, where all the devices on your network will be displayed together (and in groups, once we've implemented that feature).

> The middle row showing the Wi-Fi client config page is fine (except there won't be a mode selection on it).

See above.

> I would also show the IPv4 address after the status "Connected" if possible.

Hmm, yes it would be good to display that in the UI somewhere. But if we're going to do that we should probably also provide a way to get the current IP address for Ethernet LAN (when getting an IP address from an external DHCP server as a client) and for WAN (when getting an IP address via DHCP). I've filed #1673 for that. 

> LAN
> For the "Home Network" column, if config is "router" mode, the top row screen would show an editable "Static IPv4 address" field (but no mode nor "DHCP Server" checkbox.)

Many existing users will have their gateway configured as a DHCP client over Ethernet (that is the case for my gateway). We need to be able to represent this in the UI somehow.

> Below the config settings, it would be nice to see a list of DHCP-connected clients and their IP addresses (and "lease time remaining" as a bonus.)

WiFi devices will eventually be displayed in the Things screen (see above). DHCP lease management will come later.

> If the mode is AP or client, then the Home Network page could show the IP address that was received by the WAN (AP mode) or WLAN (client mode), since it would be bridged to that same IP, but it would just be status data since there would be nothing to configure.

Note that whether the gateway is acting as a Wi-Fi client or Access Point is orthogonal to whether it's acting as a DHCP client or server over Ethernet - the two network adapters could be configured differently.

> WAN
> For the "Internet" column, instead of "mode", the configuration drop-down option label could be something like "Internet (WAN) connection type". It would be nice to see connection status on this page, for any of the three options. If automatic DHCP, show the IP address received from the upstream router. If static (e.g., entered as 192.168.1.42), we either need to assume a subnet mask of 255.255.255.0 and upstream router with same subnet as manually entered IP address except ending in .1 (e.g., 192.168.1.1), or we should show those two additional editable fields (and automatically fill them in with defaults just described.) If PPPoE, again simply show status of the connection below the configuration fields.

I think we'll definitely add a way to find out all of this information eventually, but for now I'm trying to keep it to the bare minimum. For now you'll need to use LuCi to access this level of configuration.

> Back to the "top" light blue screen, as much status information as possible on that page would be nice.

As I explained above, my goal at the moment is to keep the UI as simple as possible, not to display all possible network information in this first iteration of network settings.

![network_settings3](https://user-images.githubusercontent.com/552417/53194618-b1616100-360b-11e9-9c4b-4982875e67d9.png)

**Comment by kgiori** [comment]
Uploading here a copy of UI screens with comments directly on them in red. If Wi-Fi client mode is selected, then WAN becomes irrelevant (since Wi-Fi becomes WWAN, equiv of WAN). Technically LAN can still be Router mode, even if Wi-Fi is WWAN. 
![gw-network-config-ui](https://user-images.githubusercontent.com/9487286/53318685-f2b07580-3884-11e9-8592-fa3cde5caab2.png)

**Comment by dhylands** [comment]
The static IP page also needs a place to enter DNS server(s) (and gateway as kgiori mentioned)

**Comment by benfrancis** [comment]
@kgiori wrote:
> If Wi-Fi client mode is selected, then WAN becomes irrelevant

It is possible to be connected to the Internet both via WiFi and the the WAN port with two separate local IP addresses.

> Technically LAN can still be Router mode, even if Wi-Fi is WWAN.

Yes

> Show WAN IP

As I said, this can be added later in https://github.com/mozilla-iot/gateway/issues/1674

> Delete checkbox sice implied when mode changed to bridge ("Router" with no DHCP service makes no sense)

It is possible for the gateway to act as a router in the sense that it provides NAT, but with DHCP disabled and each client is assigned a static IP. Most routers have an option to disable DHCP.

> Show IP address obtained

This is https://github.com/mozilla-iot/gateway/issues/1674

> Allowing Client mode doesn't make sense if LAN set to Router.

Unless the Internet connection is via Wi-Fi and clients connect via Ethernet, as you said yourself "Technically LAN can still be Router mode, even if Wi-Fi is WWAN."

> If Wi-Fi is client, LAN/WAN should bridge to Wi-Fi which is acting as Internet (WAN).

Wi-Fi acting as WAN and WAN acting as LAN? This is getting confusing...

> "Bridge" instead of Client. (This mode implies disabling DHCP server to allow passthrough of LAN-connected devices, either via Wi-Fi client or WAN as Internet link.)

It could just mean that the Raspberry Pi is connecting to the Internet over Ethernet as a client and no bridging is involved.

> Config option for DHCP/manual would occur on WAN config if Wi-Fi disabled.

I don't understand.

> So I'd like to see bridge IP addr here (obtained via Wi-Fi client mode or Ethernet WAN).

Which IP address? There could be three. This is https://github.com/mozilla-iot/gateway/issues/1674

> This page needs subnet and gateway IP settings too. To make it easier, fill in typical defaults based on the IP address that they start entering (IP should start blank).

As I said, I was trying to start with the bare minimum.

> Remove this page (client mode for LAN).

This is the current default for the Raspberry Pi, we can't remove it.

> If Wi-Fi disabled, LAN would bridge to WAN IP except in case of Router mode.

This is really orthogonal to whether or not Wi-Fi is enabled.

> Can there be status of the connection?

Yes, eventually. As I said, I was trying to start with the bare minimum (mainly just to configure a WiFi hotspot). We will add many more features later.

--

This is getting a bit ridiculous. If we want to support all of these different possible configurations then things are going to get very complicated.

I'm more and more tempted to have a different UI design for the OpenWrt version (intended for routers) and the Raspbian version (intended for the Raspberry Pi, as a client) of the gateway. That way we could have have a super simple first time setup for routers and only network settings which make sense for a router, and keep the existing first time setup for Raspberry Pi with only network settings relevant to the Raspberry Pi.

**Comment by dhylands** [comment]
Another way of thinking about things might be to ask the question:

How will this device (the router) connect to the internet? 3 answers are WAN, WiFi, or LAN

The answer to this drives most of the other choices.

My little wireless gadgets has a 2 ethernet ports and switch which says internet via wired or wireless. For wired, one of the ethernet ports is a WAN and one is a LAN, and the WiFi acts as an AP (so much like a traditional router). For wireless, both ethernet ports act as LAN ports.

**Comment by benfrancis** [comment]
Separate network settings UI for Raspbian (client) and OpenWrt (router)

Raspbian:
![network_settings-raspbian](https://user-images.githubusercontent.com/552417/53428695-2b666100-39e3-11e9-8dc3-bb711da6b848.png)


OpenWrt:
![network_settings-openwrt](https://user-images.githubusercontent.com/552417/53428714-33260580-39e3-11e9-9df9-7058d7584dec.png)

**Comment by benfrancis** [comment]
Following further team discussions I have re-designed the network settings with a different UI for Raspbian and OpenWrt builds. Raspbian builds are assumed to act as a network client (as the gateway currently does) and OpenWrt builds are assumed to act as a router.

See the UX specification [here](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g5094b10cb0_2_65).

**Comment by mrstegeman** [comment]
@benfrancis Can I get all the new icons?

**Comment by benfrancis** [comment]
[icons](https://drive.google.com/drive/folders/1hSTGXCqWbbIWCBLWIRwGAW3JO3jAJ0jS?usp=sharing):
- wifi.svg
- network.svg
- internet.svg
- ethernet.svg

**Comment by Rudower** [comment]
Hi all, 

I have a trouble with my network initialization. From time to time, I suffer short electricity blackouts at home. My router takes more time to reboot than my Raspi with the Webthings gateway. 

I read here that the trouble I have is the expected behaviour: after a bloackout, the Raspi boots and becomes alive earlier than the router, and as it doesn't find its configured wifi alive, it passes on to the network selection mode and activates itself as a wifi hotspot; hence, the Raspi turns offline the old connection and keeps it like that even when the router is back again. 

I'd be able to workaround this easily by introducing a sleep command just before the network initialization commands. I've reviewed the .bashrc, but it is not there. Is there any way to introduce a sleep command before the network intitialization?

**Comment by mrstegeman** [comment]
You could add it to `/home/pi/mozilla-iot/gateway/run-app.sh` just before `run_app` is called on the last line.
