### ISSUE TITLE
Rules with other device types

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#515]
As a user I want to make rules involving devices that aren't onOffSwitches.

**Comment by benfrancis** [comment]
Yeah I've been thinking about this, the rules engine is going to look quite limiting now we have all these device types. The scope here is potentially infinite, so maybe this should be an "epic" and we can file issues for the individual inputs and outputs we can think of. What ideas do you have so far?

Something I'm really missing is timers, starting with triggering something to happen at the same time every day, but then getting more sophisticated with sunrise/sunset, randomisation, more complex schedules etc.

Another obvious example of an input is when a "level" property reaches a certain threshold and an output being to set a level property or a color property to a certain value.

I guess this is going to require some new UI design as well, and not sure whether we can get any of this into 0.3.

**Comment by hobinjk** [comment]
I agree that timers are a good idea. There's also triggers and effects for each of the new web thing types, which means at least support for the number type in property triggers/effects.

**Comment by kgiori** [comment]
I like the new clock option. Since the clock supports AM and PM, add the "AM or PM" part to the short description that is created for the rule (or convert to 24hr format).

**Comment by dholbert** [comment]
Some concept of a "countdown timer" would be really helpful, too, whether as a "virtual device" or as a version of the "clock" in the rules editor.

* Common use-case: motion-activated lights (motion sensor activated --> turn on light), and you want them to automatically turn off N minutes after they turned on.
* My own more niche use case: I've got a hot-water recirculator which is plugged into a smart outlet in my utility room. I turn it on with my Mozilla IOT gateway, and a few minutes later, my shower has hot water ready at the tap.  Right now I have to remember to turn it off (or it'll just keep circulating freshly heated water through my pipes all day long and eat up my gas + electric bill).  I'd love to be able to have it automatically shut off after N minutes have passed since I turned it on.

**Comment by benfrancis** [comment]
I think we have this now :)

**Comment by dholbert** [comment]
Do we have the "countdown timer" type feature, or anything else that'd enable an "auto-shutoff" type rule, per https://github.com/mozilla-iot/gateway/issues/515#issuecomment-370579504 ?

(If so, awesome! If not & if that's in-scope, I'll gladly file another issue on that.)

**Comment by hobinjk** [comment]
I think it would be good to file an issue for creating an adapter or web thing that supports countdown timer style logic since I think that is a bit too complex to put directly in the rules engine.

**Comment by dholbert** [comment]
Thanks. I filed #1265 on my countdown-timer use-case.
