### ISSUE TITLE
pencil icon misaligned on floorplan page

### ISSUE THREAD

**Issue by autonome** [mozilla-iot/gateway#535]
Firefox Nightly 60.0a1 (2018-01-24) (64-bit) Mac OS x

<img width="606" alt="screen shot 2018-01-25 at 10 01 01" src="https://user-images.githubusercontent.com/50103/35404191-f004bb94-01b6-11e8-9ade-bd8a28a30f51.png">

**Comment by hobinjk** [comment]
I'm unable to reproduce this on the latest version of the gateway. Could you try updating your local copy to master or try downloading and flashing the [0.3.0-pre5 prerelease](https://s3-us-west-1.amazonaws.com/mozillagatewayimages/images/gateway-0.3.0-pre5.img.zip)

**Comment by benfrancis** [comment]
Dietrich is using 0.3-pre5. I wonder if it's a fonts thing.

On 25 Jan 2018 22:07, "James Hobin" <notifications@github.com> wrote:

I'm unable to reproduce this on the latest version of the gateway. Could
you try updating your local copy to master or try downloading and flashing
the 0.3.0-pre5 prerelease
<https://s3-us-west-1.amazonaws.com/mozillagatewayimages/images/gateway-0.3.0-pre5.img.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla-iot/gateway/issues/535#issuecomment-360616685>,
or mute the thread

**Comment by mrstegeman** [comment]
I can reproduce, but have no idea how to edit SVGs.

**Comment by hobinjk** [comment]
I think it's based on the SVG not including the open sans font. I think we include open sans in the HTML so I'm not entirely sure why it's missingOn Jan 26, 2018 11:26 AM, Mike Stegeman <notifications@github.com> wrote:I can reproduce, but have no idea how to edit SVGs.
