### ISSUE TITLE
Ikea Tradfri Support

### ISSUE THREAD

**Issue by jram0421** [mozilla-iot/gateway#626]
https://github.com/ggravlingen/pytradfri
Here is a library that would be a good start to look at, as it is what is currently used in Home-Assistant, and since I use Tradfri bulbs, this is the one thing stopping me from migrating.

**Comment by daenney** [comment]
There's also [node-coap-client](https://www.npmjs.com/package/node-coap-client) for a JS based solution that could in theory ship with the gateway itself. It's used in our [Tradfri to MQTT gateway](https://github.com/hemtjanst/tradfri-mqtt) if you'd like to draw some inspiration.

**Comment by benfrancis** [comment]
@dhylands Do we support IKEA bulbs directly via Zigbee yet? (As opposed to using the IKEA bridge).

**Comment by dhylands** [comment]
Yes - I was able to talk to one of my Ikea bulbs. They need to be factory reset, either using an appropriate remote (like the Lutron or Philips Hue Dimmer) or by using the switch. See: https://github.com/mozilla-iot/wiki/wiki/HOWTO:-Factory-reset-an-IKEA-bulb and https://github.com/mozilla-iot/wiki/wiki/HOWTO:-Factory-reset-a-Hue-bulb (for the remote/dimmer approach)

**Comment by jram0421** [comment]
@dhylands will it work with the RGB bulbs?

**Comment by dhylands** [comment]
@jram0421 I can't say for sure since I only have the bulbs which came with the starter kit. I have talked directly to color Philips Hue bulbs, so if the Ikea bulbs advertise themselves using the same clusters as the Philips ones, then they should work as well.

Can you give me the product name/number? I'm not seeing any Tradfri RGB bulbs on the Ikea web site. The Tradfri stuff only seems to support changing color temperature as far as I can tell.

**Comment by dhylands** [comment]
Interesting. They say they support 9 colors. So it sounds like they're doing something different from what Philips does, but I won't know for sure until I can look at all of the clusters and stuff. 

It looks like they don't yet sell the bulb by itself, just as part of the kit with a dimmer.

**Comment by daenney** [comment]
The IKEA RGB bulbs do full spectrum RGB though. It's just that with the remote it cycles through 9(?) presets, but you can set it to any colour as long as you send it the right stuff.

**Comment by jram0421** [comment]
@daenney the remote is limited to 9 colors. They are compatible with the Hue hub, and you could take a look at how Home assistant supports them, as it might give some inspiration

**Comment by valenting** [comment]
I was able to pair the tradfri motion sensor with the gateway. Of course, it doesn't do anything yet, but it would be very cool if support for it could be added, as it would make for very cool "if-this-then-that" scenarios.

**Comment by critaL** [comment]
Yes this would be greatly appreciated, the support for Ikea trådfri is the only thing keeping me from going all in on this.

**Comment by devwolti** [comment]
Don't want to disappoint you, but the remotes and PIR sensors do only tell you the battery state, not a button or motion event. That's why you have to pair them directly to the bulbs. You can't even pair a remote and a sensor to a bulb, you have to copy the signature(which will make one of the devices invisible to the gateway /app) . In addition the sensors seem to have a big delay to save battery. 
At least I couldn't make them talk to me. The bulbs do not have full spectrum. A part of the green spectrum is missing. Maybe we get a bit more functionality with Firmware upgrades. The workaround in the forums so far was listening to the bulb which is paired to the sensor for changes. 
Rumors say that there are E14 color bulbs coming and remote power plugs around October. But no guarantees for that. Tradfri is still in an early stage of development. I'll try the Mozilla suite again next week. Let's see.

**Comment by mrstegeman** [comment]
Moved: mozilla-iot/zigbee-adapter#41

**Comment by tim-hellhake** [comment]
The Tradfri gateway is now also supported:
https://github.com/mozilla-iot/addon-list/pull/577
