### ISSUE TITLE
Add-on list should show the version number of each installed add-on

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#643]
Currently, you see the list of installed addons, and a description, but no version.

**Comment by dhylands** [comment]
Similarly, the install an addon screen should show version numbers as well.

**Comment by benfrancis** [comment]
Please add the ui-needed label in future to feature requests which require a change in the UI. Otherwise the UI mockups will get out of sync with the implementation and it will be difficult to know how the UI is supposed to behave.

@mrstegeman  Can you add a screenshot here of the UI design you implemented?

**Comment by mrstegeman** [comment]
![screen shot 2018-02-12 at 07 35 21](https://user-images.githubusercontent.com/457381/36101720-0d2eab2c-1002-11e8-89a9-e7ace3d3be80.png)
![screen shot 2018-02-12 at 07 35 39](https://user-images.githubusercontent.com/457381/36101721-0d4b25cc-1002-11e8-91f7-f4827045338a.png)
