### ISSUE TITLE
Unable to connect to gateway.local

### ISSUE THREAD

**Issue by KWierso** [mozilla-iot/gateway#646]
I recently bought a RPi3 and flashed the OS and started up First Time Setup.

I connect to the Mozilla IoT Gateway network, and it opens a tab in my browser, asking for my wifi credentials. I set it up, and the page asks me to reconnect to normal wifi and go to gateway.local.

I just get 404 errors trying to connect to gateway.local. I'm not sure what diagnostic info I can try. I did this with the RPi3 connected via wifi and with it hardwired over ethernet.

**Comment by KWierso** [comment]
Is there a way to go through First Time Setup again without having to spend 10 minutes reflashing the SD card? I've done that a few times now to try again, but I'd like to just rerun setup. I'm not sure if that's possible since the Mozilla IoT Gateway SSID disappears once I've selected a wifi network to use.

**Comment by dhylands** [comment]
You could remove the network from the /etc/wpa_supplicant/wpa_supplicant.conf file. You need to be root to do this (i.e. use sudo). The network entry will look something like:
```
network {
  ssid="my-ssid"
  psk="my-network-key"
}
```
Remove all 4 lines. If you have a linux machine then you can edit the wpa_supplicant.conf file on your host machine, otherwise you'll need to login to the Pi. See this page: https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi

Once you get logged in, it would be good to get the output of `ifconfig`.

**Comment by mrstegeman** [comment]
Closing. Please re-open if the issue occurs again.
