### ISSUE TITLE
Is the z-way gpio board compatible with Mozilla’s Things Gateway

### ISSUE THREAD

**Issue by mondiaan** [mozilla-iot/gateway#647]
Hi,

I already have a Z-way extension board for the raspberry.
Can I use this HardWare instead of a USB z-wave dongle?

Regards,

Bas

**Comment by mrstegeman** [comment]
Theoretically. OpenZWave lists it as supported: https://github.com/OpenZWave/open-zwave/wiki/Controller-Compatibility-List

@dhylands have you tested with this board, by chance?

**Comment by mrstegeman** [comment]
Here's some info on how to set up the daughter board on the RPi, which will probably be necessary for OpenZWave to recognize it: https://www.vesternet.com/resources/application-notes/apnt-85#.U_4xlxYU58E

NOTE: You probably just need to follow the "Configure RaZberry PI GPIO Daughter Card" section. The rest is about some other software.

**Comment by dhylands** [comment]
I haven't tested it. I suspect that it won't work "as-is".

The way that the code currently works, it looks for serial adapters with particular VIDs and PIDs ont he USB bus. We need a way to configure the z-wave adapter and tell it to use a particular serial port, since the board in question would connect via the TTL serial port on the GPIO headers. We would also need to disable the serial console.

**Comment by mrstegeman** [comment]
Closing in favor of https://github.com/mozilla-iot/zwave-adapter/issues/8
