### ISSUE TITLE
Feature Request: Add Custom Links to Floor Plan

### ISSUE THREAD

**Issue by DankRadon** [mozilla-iot/gateway#658]
With GET URLs we could control our devices through Smartthings Webcore or IFTTT webhooks.
I created a mock-up prototype in Adobe XD
[https://xd.adobe.com/view/d081d0b5-0932-464e-8128-8b5ac2345847/?fullscreen](https://xd.adobe.com/view/d081d0b5-0932-464e-8128-8b5ac2345847/?fullscreen)
Hint: click the [Add URL] button, then click the Name field.

**Comment by benfrancis** [comment]
I'm not sure I understand what you mean by custom links?

We are planning to add a feature to add web things by their web thing URL.

But are you suggesting adding virtual thing icons to the UI which make HTTP requests using non-standard APIs? If so, I don't think we'd do that because we're trying to promote a common [standard](https://iot.mozilla.org/wot/) for the Web of Things.

**Comment by benfrancis** [comment]
A better way to think about this type of integration is that IFTTT rules can call the Web Thing API on the gateway, not that the gateway can act as a user interface for IFTTT.
