### ISSUE TITLE
Need a mechanism to input a PIN during pairing

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/gateway#668]
For things like Bluetooth or HomeKit, the user will need to input a device-specific PIN code while pairing with a given device.

**Comment by mrstegeman** [comment]
For HomeKit in particular, we need a PIN _before_ we can generate a thing description. So in the _Add Things_ screen, we may need to add the ability to asynchronously display a PIN request. We can include some model/manufacturer data, so the user knows what the device is, at least.

**Comment by sogaani** [comment]
Some add-ons need configuration like PIN to add thing.
* [knx-addon](https://discourse.mozilla.org/t/knx-addon-question/27267/11)
* [thing-url-adapter](https://github.com/mozilla-iot/thing-url-adapter)
* [gpio-adapter](https://github.com/mozilla-iot/gpio-adapter)
* [broadlink-adapter](https://github.com/sogaani/broadlink-adapter)

The difference of HomeKit/Bluetooth and above adapters is whether to display actual device-specific information like model/manufacturer.

Just like add-ons configuration, I want to develop allowing define schema for things configuration after 0.4 release.
So, we can support any configuration to add thing with a common mechanism.

**Comment by mishoboss** [comment]
Is there some draft described somewhere? Does anybody work on it?

**Comment by sogaani** [comment]
I still not work on. I will start next week.

**Comment by sogaani** [comment]
I want to make some API for addon for providing device config.

* `Adapter.getConfiguarableDevice`
    * When called
      * When `get /new_things` called or adapter added.
    * Return
      * `Promise<Array<{Object: schema, Object: description}>>`
    * Description
      * The `schema` is formed by JSON schema and indicates what the user should input.
      * The `description` is optional and a part of things description. If a `description` contains `type` or `name`, we can provide some information for user when adding configurable device.

* `Adapter.addDevice`
    * When called
      * When `post /new_things` called or adapter added.
    * Params
      * `config`
      * `description`
    * Description
      * The `config` is what is inputted by  the user and formed by JSON schema.
      * The `description` is a things description as was returned by `Adapter.getConfiguarableDevice`.
      * When called, the Adapter should make the devices using `config` and call `Adapter.handleDeviceAdded`.
      * The Gateway should hold `config` until deleted by the user in order to provide `config` to the adapter when restart the Gateway.

* UI representation.
  1. If the adapter provides `schema` and `description`, UI will show a thing which containing a configure button in add things screen. When the user configured things, UI will call `post new_things` and delete thing which configured. Few seconds later a things added by adapter will be shown.
  2. If the adapter provides `schema` only, UI will show the texts provided by schema along with add button in add things screen. When the user press add button and configured, UI will call `post new_things` and keep texts and add button. Few seconds later a things added by adapter will be shown.

* Usecase
  1. If the addon provides devices which is known by an addon and need configuration like pairing key, the addon should return `schema` and `description`.
  2. If the addon provides devices which is not known without user configuration like `thing-url`, the addon should return only `schema`.

Feel free to give me any issues or suggestions about this.
I am wondering whether `description` should be more freedom to show useful data like model/manufacturer.

**Comment by mishoboss** [comment]
Looks good. What about editing config data after device is added?

Also one more thing - this approach expects that things are auto discovered and they will report what they are and what their configs are. However there are cases when we don't have auto-discoverable devices, like in KNX or MySensors. Probably this is good to be discussed somewhere else, but there should be a mechanism to manually add and config such devices via the same approach - JSON-SCHEMA config.

**Comment by sogaani** [comment]
@mishoboss 
Thanks your feedback.

> What about editing config data after device is added?

I think that not all devices need editing, e.g bluetooth paring code will not change, and we can edit config by property or action if want. Could you tell me some usecases which is not suitable editing config by proprty or action?

> Also one more thing - this approach expects that things are auto discovered and they will report what they are and what their configs are. However there are cases when we don't have auto-discoverable devices, like in KNX or MySensors. Probably this is good to be discussed somewhere else, but there should be a mechanism to manually add and config such devices via the same approach - JSON-SCHEMA config.

I will support cases that we can not auto discover devices with above APIs.
If addon can not auto discover devices, addon can return only `schema`.
Should we split APIs?

I wrote above. 
> If the adapter provides schema only, UI will show the texts provided by schema along with add button in add things screen. When the user press add button and configured, UI will call post new_things and keep texts and add button. Few seconds later a things added by adapter will be shown.

**Comment by mishoboss** [comment]
> I think that not all devices need editing, e.g bluetooth paring code will not change, and we can edit config by property or action if want. Could you tell me some usecases which is not suitable editing config by proprty or action?

I think you idea editing by property or action is even better. Is that going to be possible with this new API?

> I will support cases that we can not auto discover devices with above APIs.
> If addon can not auto discover devices, addon can return only schema.
Schema of what? Where that device is described? You see, that's the point - in KNX we don't know the device. User should somehow manually chose what is the device he wants to add - is it a roller shutter, is it a light, is it ON/OFF window sensor, thermostat? We don't know, cause KNX protocol doesn't provide such data. KNX doesn't care. Maybe there should be some predefined list of devices and user choses one of them, then the schema of the chosen device is supplied for additional config of KNX Groups Addresses?

**Comment by sogaani** [comment]
> I think your idea of editing by property or action is even better. Is that going to be possible with this new API?

Oh, I was confused. Since I say that The Gateway hold device config, we need new API which edit config as you say. I think we need `database.getDeviceConfig` and `database.setDeviceConfig`.

> Schema of what? Where that device is described? 

JSON schema is flexible enough to construct configurations depending on device type.
I wrote the addon config depending on device type [here](https://github.com/mozilla-iot/wiki/wiki/Add-On-Configuration#configuration-which-have-dynamic-form).
This example is addon config, but device config will have same flexibility because of using JSON schema.

**Comment by mishoboss** [comment]
> JSON schema is flexible enough to construct configurations depending on device type.
I wrote the addon config depending on device type here.
This example is addon config, but device config will have same flexibility because of using JSON schema.

Got it. That will do the job, I think. We will have a list of predefined devices with their config fields. The list will be rendered as a dropdown. User choses a device from that list and its config fields are rendered below. Should work in theory! :)

**Comment by sogaani** [comment]
Good!
I will start implementation from tomorrow.
There is a possibility of change, if anyone will have any issues or suggestions.

**Comment by mishoboss** [comment]
Great, just one thought. Probably the adapters that provide non-discoverable devices should be flagged as `discoverable: false`. Then, when user presses the "+" button to add devices, all non-discoverable adapters should provide a way to add a device, similar to how you already do it with manually added web thing:

![image](https://user-images.githubusercontent.com/1629929/39765552-c96bf1e8-52ea-11e8-87e9-1a3438a87346.png)

**Comment by benfrancis** [comment]
Work in progress UI design:

![enter_pin](https://user-images.githubusercontent.com/552417/39833721-ce9d1c04-53c2-11e8-86b0-3ded31d41cb2.png)

@sogaani Thanks for looking at this. Note that this issue is specifically about the use case of entering a pin during pairing (.e.g. for Bluetooth and Webkit). We should discuss this further before generalising it to the more general use case of things which require configuration to be entered while adding them to the gateway. The solution you've described (using JSON Schema to automatically generate UI for arbitrary input fields) sounds quite complex.

It sounds like there might be a separate use case around some classes of device (e.g. KNX) for which the user needs to manually add a device entry, rather than scan for devices on a network. We should probably deal with that separately.

The kind of flow you're describing where arbitrary user input is described using JSON Schema sounds a lot like an [action input](https://iot.mozilla.org/wot/#action-object) on the Web Thing API. Perhaps that could be implemented as an action on the gateway, where the gateway gets its own Thing Description (something we talked about before). But I'd like to better understand the intended use cases before designing a complex API for this purpose. Can you explain your thinking in a bit more detail, and perhaps file a separate issue for the more general requirement of entering configuration while adding a device?

**Comment by sogaani** [comment]
@benfrancis Thank you for replying. I file issue separated https://github.com/mozilla-iot/gateway/issues/993.
I'd appreciate it if you could give me your opinion.

**Comment by benfrancis** [comment]
@sogaani Thanks, I will take a look.

Final UI specification for "enter PIN during pairing" [added](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g3b5aa6b68a_1_0), mockups below:
![enter_pin_flow](https://user-images.githubusercontent.com/552417/40543384-0341a0aa-601c-11e8-8159-ce3f8da68546.png)
