### ISSUE TITLE
433Mhz transmitter/receiver adapter

### ISSUE THREAD

**Issue by higgleradolf** [mozilla-iot/gateway#682]
Hi,
I'm trying to use the 433Mhz adapters, which are directly connected to the GPIO ports. This has worked in Fhem. But it's Not working on Mozilla Iot yet.
(https://www.amazon.com/gp/aw/d/B06XKVF755/ref=mp_s_a_1_10?ie=UTF8&qid=1518683275&sr=8-10&pi=AC_SX236_SY340_QL65&keywords=burglar+alarm+433mhz+Transmitter)
Anyone an idea toll make it run?

**Comment by thetwc** [comment]
Or how about the rfxcom 433 USB adapter?  Could that be made to work?

**Comment by richardvanderpol** [comment]
Yes, a 433 Mhz transmitter plugin would be very nice! 
Something like the Homeduino plugin that Pimatic uses?
https://github.com/pimatic/homeduino
Keep up the good work peeps! :-)

**Comment by flatsiedatsie** [comment]
I created a very simple [plugin for Domoticz](https://github.com/flatsiedatsie/433Switches) that can clone and re-transmit 433Mhz signals on the Pi. It works great for controlling simple 433 Mhz sockets.

Perhaps that's a simple way to go here too?

**Comment by sindastra** [comment]
I too have devices that use 433 MHz, specifically door sensors, remote controls and the "base station" by tiiwee. So I too am interested in getting a 433 MHz adapter to work.

I'd be willing to help and invest some time and resources.

**Comment by flatsiedatsie** [comment]
I have this working via MySensors. I've created some Arduino code that can copy almost any 433Mhz signal and replay it. Alternatively, it can also learn to recognize 433 codes, and then notify when this occurs.

You can find out more here:
https://forum.mysensors.org/topic/10094/candle-signal-hub-a-universal-433mhz-signal-detector-and-cloner

**Comment by flatsiedatsie** [comment]
I think this issue should still be open.

Yesterday I gave a workshop in which participants together created the Candle smart home system.
The participants were happily surprised by the WebThings Gateway. All had never heard of it. Most of the hackers with smart home/caravan systems (not joking) were using Home Assistant (2x) or Domoticz (1x).

We discussed switching their homes to the WebThings Gateway. They were happy to see the long and growing list of add-ons. But two add-ons were missing for them to try and make the switch:
- Sonoff support (1x)
- 433 Mhz support (3x)

They said things like "I have a lot of 433 Mhz devices that I don't want to leave behind". The devices were said to be "a left-over from when they started their smart home adventures", but they also still bought them because they were cheap. One participant mentioned needing 20 window and door sensors, and those being much cheaper when using 433 instead of Zigbee. Wall sockets were also said to be expensive - here in the Netherlands you can get three 433Mhz sockets for 10 euro at the local Action store.

Two of the three participants mentioned using the RFXCOM 433 USB stick, which costs up to 100 euro but has broad support. 

Personally I've used the [RFLink](http://www.rflink.nl/blog2/) system, which is based on an Arduino Mega, and can be made for about 15 euro.

Either way, having some support would seem to go along way in enticing users to switch to the WebThings Gateway.

**Comment by mrstegeman** [comment]
It seems like this would be better filed against the [RF433 adapter](https://github.com/tim-hellhake/rf433-adapter). @tim-hellhake would probably be more than willing to add missing device support.

**Comment by tim-hellhake** [comment]
@flatsiedatsie

> One participant mentioned needing 20 window and door sensors, and those being much cheaper when using 433 instead of Zigbee

Those should already work with rf433 adapter.
All you need is a cheap 433MHz receiver and a raspberry pi.

> But two add-ons were missing for them to try and make the switch

Why two? Aren't the sonoff devices generic 433MHz devices?

**Comment by flatsiedatsie** [comment]
@mrstegeman While Tim's adapter is a great start, it's very different from RFXCOM or RF-Link support.

Basically there are three things you'd want:

1. Recognition of sensors that emit fixed codes. This can be done by using a library, or by creating a universal pattern recogniser.
2. Transmission of codes to toggle power sockets. This can be done by using a library, or by creating a universal pattern cloner.
3. Recognition of data from devices that transmit data over 433, such as outdoor weather stations. This can be done by using a library that understands the numerous protocols.
4. Transmission of data to devices that transmit data over 433 and use specific protocols. For example, thermostats.

Right now users could use Tim's add-on, which supports 1.
They could also create the [Candle Signal Hub](https://www.candlesmarthome.com/signal-hub), which supports 1 and 2.

Howver, only the RFXCOM and RF-Link systems have wide support for all four things. For example, have a look at the [latest RF-Link blogposts](http://www.rflink.nl/blog2/) to get a feel for the incredible amount of devices and protocols out in the wild.

It's difficult to understate the complexity of creating wide support. Both of these systems have been learning and adding protocols for years.

My recommendation would be to expand Tim's addon to support 1&2. This will be sufficient for 80% of users.
For the other 20%, an add-on that interfaces with the RFXCOM or RF-Link would bring 433Mhz support to complete.

Also, don't forget that of all these solutions, only the RFXCOM is a USB stick that you simply plug in. It's the only one that is consumer-proof. All the others require fiddling with electronics.

**Comment by mrstegeman** [comment]
@tim-hellhake Thoughts?

**Comment by tim-hellhake** [comment]
@mrstegeman @flatsiedatsie

> My recommendation would be to expand Tim's addon to support 1&2.

Adding the transmitter part is already on my to-do list.

> For the other 20%, an add-on that interfaces with the RFXCOM or RF-Link would bring 433Mhz support to complete.

I'll have a look at the RFLink.
