### ISSUE TITLE
Reword the installation procedure to allow HTTPS

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#691]
Prompted by #688 Activate HTTPS by Default?

> Connecting the browser to the IP address and not the `.local` address implemented HTTPS.
> 
> However, just after page **Connect to a WiFi network?**, the installation procedure suggests to connect to `gateway.local` instead of the IP address.
> 
> <img width="400" alt="capture 2018-02-18 a 18 53 26" src="https://user-images.githubusercontent.com/951776/36355085-f2b87c4c-14dd-11e8-9200-71d379997374.png">
>

**Comment by benfrancis** [comment]
There should be difference between using the local IP address and a .local domain. In either case you need to accept a security exception in the browser.

**Comment by rei-vilo** [comment]
> Initial setup is over plain HTTP. Once configured, the gateway redirects to HTTPS and you need to accept a security exception if accessing the gateway over a local IP address or .local domain.

The gateway didn't redirected me to HTTPS when I selected `gateway.local`. It did it when I connected to the IP address directly, *e.g.* `192.168.1.141`.

As the HTTPS certificates are auto-generated, the browser checks and asks for a security exception.

**Comment by benfrancis** [comment]
> The gateway didn't redirected me to HTTPS when I selected gateway.local. It did it when I connected to the IP address directly, e.g. 192.168.1.141.

There should be no difference, so that would be a bug. If you can provide steps to reproduce then we can look into it.

> As the HTTPS certificates are auto-generated, the browser checks and asks for a security exception.

The only automatically generated certificates are those generated for *.mozilla-iot.org domains and they will not match a local IP or .local address which is what gives you an exception. You can manually generate self-signed certificates on the command line to use locally if you wish, but this also generates a browser exception.

**Comment by rei-vilo** [comment]
Steps are in #688.

**Comment by benfrancis** [comment]
Could it be because you modified the hostname to be mypimozilla.local instead of gateway.local?

**Comment by rei-vilo** [comment]
It could be. In any case, it should be documented: do not change the name of the gateway!

**Comment by benfrancis** [comment]
The installation procedure does allow HTTPS when using the recommended subdomain and tunnelling service.

HTTPS does not work on local networks.

**Comment by benfrancis** [comment]
I think the user interface is correct, the problem was caused because you changed the hostname on the Raspberry Pi on the command line before going through the setup process. This shouldn't be possible if using the UI as intended.

If you think there's still a bug then please list the steps to reproduce, the expected outcome and the actual outcome. As far as I can tell the gateway is behaving as intended. Sorry if I misunderstood.

**Comment by rei-vilo** [comment]
Thank you for your reply. Listing the steps to reproduce, the expected outcome and the actual outcome would mean I had to redo the whole process a couple of times more, and I went though it half a dozen times already.

**Comment by benfrancis** [comment]
Fair enough. As far as I can tell I don't think there's a bug here, it should work as expected if you follow the instructions on this [blog post](https://hacks.mozilla.org/2018/02/how-to-build-your-own-private-smart-home-with-a-raspberry-pi-and-mozillas-things-gateway/).

If you enable SSH on the device (which is disabled by default) there are any number of commands you could type which would stop the setup process from working, we can't possibly document them all :)

If you do find a reproduceable bug then please let us know.

**Comment by dhylands** [comment]
If you renamed the gateway to mypimozilla then you need to connect to https://mypimozilla.local 
The gateway software could query the hostname and show that on the UI rather than using a hardcoded gateway.local
