### ISSUE TITLE
Flip-Flop Implementation?

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#694]
I have the following configuration:
- one push button (GPIO 18) and
- a LED (GPIO 17)

<img width="400" alt="capture 2018-02-19 a 21 05 03" src="https://user-images.githubusercontent.com/951776/36397814-6e200c9c-15c4-11e8-997b-83cc2e1e2dfe.png">

I would like to toggle the LED with the push button acting as a "flip-flop", _e.g._
+ Initial state: LED is off.
+ Push button pressed then released: LED turns on.
+ Push button pressed then released: LED turns off.
+ ...

How to achieve that? How many rules, and which ones, do I need to define?

_This question might be related to #693._

**Comment by kgiori** [comment]
Currently the rules engine shows properties for web thing types, but not the ability to track or trigger an "action". The onOffSwitch thing type definition has an "action" called "toggle" which changes its "on" property to the alternate state. The onOffLight does not have such an action in its definition. Maybe it should? It seems that the type of rule you describe wanting would work if the toggle action of one device was tied to the toggle action of another device.

If a pushbutton is attached to GPIO 18, then instead of defining it as an onOffSwitch, I would rather see a new thing type defined that better describes how a pushbutton works. A pushbutton "toggle" event would be triggered by "off-on-off" (low high low) changes in voltage on the pin, not a simple off-on or on-off (low to high, or high to low).

Even without a pushbutton thing type, you could detect the pushbutton off-on transition (by detecting the "on" state becoming true). What's missing is an onOffLight action of "toggle", and the rules engine allowing you to select an action as the triggered event.

**Comment by rei-vilo** [comment]
Thank you for the explanations. I know **Rules** are at an early stage of beta. 

An action is just a change of state. The priority of state over action should be clearly documented to avoid any misunderstanding, as `State` and `action` are common concepts, most of the time implicit.

On the screen-shot below, the rule says `If Button 18 is off then turn LED 17 off`.
<img width="400" alt="36395963-16d0396a-15bc-11e8-91e4-1e9ef6f8b9a5" src="https://user-images.githubusercontent.com/951776/36452130-8d917456-1693-11e8-873e-8798ace1f856.png">

So adding `If Button 18 is off then change state of LED 17` (change off to on, change on to off) would fit the flip-flop task.

How do those explanations match with the example provided in #693?

**Comment by rei-vilo** [comment]
@mrstegeman The ticket has been changed to **closed** then **done**.

+ Could you please explain how to use this feature? 
+ In which release is it going to be available? 
+ Where can I find the related documentation?

Thank you!

**Comment by mrstegeman** [comment]
I do this exact thing with some lights in my house, using a Flic button.
* Rule 1: If light is off and button pressed, turn light on
* Rule 2: If light is on and button pressed, turn light off

**Comment by rei-vilo** [comment]
Thanks!

Even better with screen-shots:

<img width="1241" alt="Capture d’écran 2019-12-28 à 19 07 08" src="https://user-images.githubusercontent.com/951776/71547836-5c1d7b00-29a5-11ea-8832-57ec543ef860.png">

<img width="1241" alt="Capture d’écran 2019-12-28 à 19 07 13" src="https://user-images.githubusercontent.com/951776/71547837-5cb61180-29a5-11ea-8cfc-2bb707d3ae7b.png">

**Comment by mrstegeman** [comment]
Exactly! Apologies for the lack of comments.

**Comment by rei-vilo** [comment]
No problem, I posted the screen-shots so other users can share the solution.

Actually, the solution is provided by the rule engine that accepts multiple conditions. 

I didn't know the rule engine offered that feature. I discovered it today.

Maybe room for a pointer to the rule engine documentation?

**Comment by mrstegeman** [comment]
https://iot.mozilla.org/docs/gateway-user-guide.html

**Comment by rei-vilo** [comment]
For coming visitors: look at section **IV. Rules: Automate Your Home** 

> When you have more than one input parameter, you can select “And” or “Or” as the logical condition to tie together the input parameters.

**Comment by freaktechnik** [comment]
Note that this approach can lead to infinite loops if both conditions are properties. So it is important that one of them is an event (and I think that I infact had a ticket open for events being able to still cause momentary loops)

**Comment by rei-vilo** [comment]
Yes, I am not fully happy with this solution.

- I hope the `press` event corresponds to the button going from `released` to `pressed`, not the the `press` state. 

This is similar to issue [#693 Question: Do Rules Transfer State or Action](https://github.com/mozilla-iot/gateway/issues/693) and thread
[Discussion: Possible Confusion between State and Action on Devices](https://discourse.mozilla.org/t/discussion-possible-confusion-between-state-and-action-on-devices/25680)

- Also, the button needs to be debounced properly.

**Comment by mrstegeman** [comment]
@rei-vilo All of that is entirely dependent on the device and add-on.
