### ISSUE TITLE
Feature Request: Add Support for Touch-Screen

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#706]
The idea is to use the touch-screen attached to the Raspberry PI 3 and mounted on a wall.

The Raspberry PI 3 has a [very nice 7" touch-screen](https://thepihut.com/products/official-raspberry-pi-7-touchscreen-display) and a [case with wall-mount holes](https://thepihut.com/collections/new-products/products/raspberry-pi-official-7-touchscreen-case).

![102035_1024x1024](https://user-images.githubusercontent.com/951776/36601727-204870be-18b6-11e8-8abc-98581ec384d0.jpg)
 
The distribution `0.3.0` does not include the desktop by default.

**Comment by benfrancis** [comment]
Hi @rei-vilo,

It's interesting you should suggest this because I have this exact touch screen and case currently sat on my desk, being used as a controller for the Things Gateway:

![img_20180223_153756](https://user-images.githubusercontent.com/552417/36602415-e713dea6-18af-11e8-9683-36c9320cf6c8.jpg)

However, I would not recommend adding a touchscreen directly to the gateway.

The gateway software is a web server, not a web client, and is intended to run on a headless hub or home router which can be placed out of sight in one central location in your home, perhaps next to where your Internet connection physically enters the building. In contrast you may want multiple smart displays and smart speakers around the home, on worktops, coffee tables, bedside tables or mounted on walls.

The biggest problem is that the kind of software stack best suited to a network gateway (vanilla Linux, OpenWrt etc.) is not the best software stack suited to a touch screen device. I'm not sure if you've ever used a touch screen with Raspbian, but it isn't a great experience because Raspbian has a desktop environment (which as you noticed we don't currently include) with a mouse cursor which is intended to be used with a keyboard and mouse.

The Raspberry Pi touch screen controller I'm using is actually running Android Things, with a custom system UI which simply provides a status bar and basic browsing controls (back, home, reload) and loads the Things Gateway interface inside a webview. Android Things provides the touch screen driver, networking, audio and graphics stack, on-screen keyboard and OTA update system.

Unfortunately vanilla Linux distributions like Raspbian do not have very good support for touch screen devices. Particularly problematic for Mozilla is that Gecko has a limited set of widget layers which can render web content on Linux. The gtk widget layer is intended for desktops and the android widget layer is intended for touch screens. If we wanted to use a Gecko-based touch screen client, it really needs to be running Android. Otherwise we basically need to re-build Firefox OS again from scratch, which I would love to do but is not going to happen.

Rather than add a touch screen (or any kind of direct user interaction) to the gateway, we are instead exploring the concept of a separate Things Controller, which could be a mobile app, a smart speaker or a smart display. My personal view is that this should be built on Android Things.

However, you're not the first person to suggest adding a touchscreen or microphone directly to the gateway. If someone can demonstrate a software stack which can run on a router *and* render web content to a touchscreen with performance equivalent to Android then I would love to be proved wrong! It is certainly technically possible, but probably not with the kinds of resources we currently have.

**Comment by rei-vilo** [comment]
Thank you for the detailed answer. 

I agree with you that the touch management on the Raspberry Pi isn't very convincing. However, I managed to use a Node-RED dashboard with Chrome running in kiosk mode, and the overall user experience was good.

Now, from a cost perspective, a Raspberry PI 3 + 7" screen + wall-mounted case combo goes for GBP107/EUR122/USD150 and is much more expensive than an entry-level 7" tablet running on Android, which starts at as low as GBP26/EUR30/USD37 and provides a much better experience.

**Comment by benfrancis** [comment]
I have created a separate [things-controller](https://github.com/mozilla-iot/things-controller) repository to discuss the potential features of a Things Controller project.
