### ISSUE TITLE
Unknown Thing view doesn't handle properties with spaces in `name`

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#732]
A person who was emailing me decided to make their properties have names with spaces which makes the input id sad since it uses name unescaped

**Comment by benfrancis** [comment]
When you say "name", do you mean the object key, or a human readable `name` field in addition to the key? A human readable property name should obviously be allowed to have spaces, but the key should not because it's more like an ID.

Mozilla's current [Web Thing ](https://iot.mozilla.org/wot/#web-thing-description)API spec doesn't have a separate `name` field for properties, but we have proposed one in the [JSON-TD](http://w3c.github.io/wot/proposals/json-td/#property-object) specification. I can't remember but our implementation may already support this? (Struggling to keep track of the differences between all these specifications!)

**Comment by hobinjk** [comment]
Oh, hmm. I thought the `name` field was referring to a human readable `name` field but it's actually being used as the key after being specified as `{name:'thatProperty'}`. I guess this doesn't warrant changing anything for now.

**Comment by benfrancis** [comment]
Out of interest, where have you seen the name of a property specified as `{name:'thatProperty'}` ?

**Comment by hobinjk** [comment]
It looks like it's mostly my fault from https://github.com/mozilla-iot/virtual-things-adapter/blob/master/virtual-things-adapter.js#L158. There is also a name property in https://github.com/mozilla-iot/example-adapter/blob/master/example-plugin-adapter.js#L184
