### ISSUE TITLE
Gateway Response Time

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#752]
For the basic project based on the GPIO adapter, with two GPIOs connected to a breadboard: 

+    pin `17` as output for LED,
+    pin `18` as input for button.

![mozilla-1_orig](https://user-images.githubusercontent.com/951776/37288671-28cd9598-2608-11e8-8ff0-6a45947e8315.jpg)

Here are the measures:

Measure | ms
-- | --
Average | 56,769
Standard Deviation | 22,250
Count | 19,000
Median | 55,706
Max | 105,826
Min | 32,597
Max-Min | 73,229

Is there any plan to improve response time and reduce the jitter?

**Comment by benfrancis** [comment]
We of course want to improve performance wherever we can.

Can you please explain what exactly you're measuring and how you measured it?

**Comment by rei-vilo** [comment]
Sure. I'm using a logic analyser, with one channel connected to the button and another to the LED.

On the gateway, a rule says `If Button 18 is on then turn LED 17 on.`

I'm pressing and releasing the button, and measuring the time between the change of state of the button and the change of state of the LED.

![capture 2018-03-13 a 15 00 38](https://user-images.githubusercontent.com/951776/37346336-5800e91a-26cf-11e8-9140-775c906e05af.png)

Of course, as the GPIOs are managed by the Raspberry Pi, the times measured include: Raspberry Pi reading the button, driver to the gateway, gateway applying the rule, driver from the gateway, Raspberry Pi turning the LED on or off.

I have no problem with the maximum time is ~100ms. The only worry is about the jitter (minimum = 32 ms, maximum = 106 ms), rather high compared to the median or average (median = average = 56 ms).

Please find the trace to be opened with the [Saleae Logic application](https://www.saleae.com/downloads).

[Gateway Response Time.logicdata.zip](https://github.com/mozilla-iot/gateway/files/1807118/Gateway.Response.Time.logicdata.zip)

**Comment by hobinjk** [comment]
Fascinating! Thanks for looking into this in so much detail. I think the jitter is caused by the amount of event loop iterations required to get from reading the button to turning the LED on being highly variable. I'd be interested in taking a close look at where the inefficiencies are.

I think the most likely explanation for the bulk of the jitter is that the the rules engine uses the Gateway's https API instead of directly manipulating the Thing objects. While we could just integrate the two more, any improvement to the performance of the API would carry over to all of the Gateway's clients.

**Comment by benfrancis** [comment]
This should hopefully have improved in the 0.7 release.
