### ISSUE TITLE
Mozilla IoT architecture - Services concept

### ISSUE THREAD

**Issue by aragnac** [mozilla-iot/gateway#802]
refer to #788

In fact what I'm trying to establish is the complete sequence of calls, the complete architecture, from the API call to the things. So now I understand that the thing-controller handle the request (PUT, GET, ...) but as I can see it's only check if the query is well formated.

Is the thing directly link to a specific adapter or is there a way to decide ,from an upper layer (for example : the thing-controler) and based on information provide in the query, to redirect this query to a service (based on a service concept) which will achieve some operations before calling the right adapter which will then send the information to the right thing. 
What I want to achieve is to reduce/split the role of the adapter by giving some more stuff to do to a service, just to seperate a little bit more all the things. The adapter will be consider only as a driver if you want.

Another diagram to explain what I mean: 

![architecture](https://user-images.githubusercontent.com/12186566/37824927-77cae496-2e8e-11e8-87df-4e862510a47b.png)

A concrete example (follow the green arrows): 

![example](https://user-images.githubusercontent.com/12186566/37825544-84c63bda-2e90-11e8-89ab-9800404f96f8.png)

In this example, I only use internal services to translate my action into gcode. But as you can see, services won't be call each time, it'll depends of the use case. 

We can imagine, for the same example, to have an external services (for example, call from the cloud) which take some video or pictures as input (corresponding to a human action, for example with is hand in front of the camera) and provide some data in output(in this case, also GCode) which can be understand by the right adapter. 
We can imagine to call services for whatever we want.

So, is there a concept of services (Cloud based, internal or external) already present in the mozilla iot architecture, is the service concept part of the pylosophy of the mozilla iot ? 

What I'm asking is probably a bit tricky. I tried to be as precise as possible.

Best regards, 

Nicolas

**Comment by sogaani** [comment]
I am interested in service you said.
I am developing an external service to connect gateway with google assistant.
My service judges which thing to issue based on voice input and calls the API defined by [wot](https://github.com/mozilla-iot/wot).
The function of this service is "Selection of appropriate things" and  "Translate from input(voice in my service) to call API defined by wot".

I think that the service for gateway has these functions, but is the internal service a bit more complicated?

As the internal service calls the adapter, the predefined API is required, so it seems necessary to define new an API that takes Gcode as an input in the example of your diagram.
Which do you intend [adapter API](https://github.com/mozilla-iot/wiki/wiki/Adapter-API) or [things API](https://github.com/mozilla-iot/wot)?

In your example ,since adapter with Gcode as input is limited, it seems good to define things API and implement it as an external service rather than an internal service.

**Comment by dhylands** [comment]
I guess I don't see the point of creating this internal service. The API to talk to the adapters is not intended to be published. The ONLY API which is published is the REST API. That is the service that anything external should be using.

The AddonManager is the only piece of code which talks to the adapters. No other code does. So in your picture the "Other internal services" bubble doesn' exist and the "Other Adapters" would connect to the bubble beside it (Internal Services) which is the AddonManager,

**Comment by aragnac** [comment]
Thanks for you answers ! 

@sogaani this is exactly what I try to do, work with an external service to manage data recieve from a web application (for example) before calling the REST API.

@dhylands my internal service was an example, I tried to understand how it works inside the gateway and therefore you answer helped me. thanks!
