### ISSUE TITLE
Wildcard Let's Encrypt SSL

### ISSUE THREAD

**Issue by mishoboss** [mozilla-iot/gateway#838]
Let's Encrypt introduced wildcard certs some days ago: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

This allows now to have SSL on all subdomains like `*.domain.com`, so no need to generate a cert on the gateway for each and every subdomain.

**Comment by mrstegeman** [comment]
The problem with doing that is that the SSL tunnel to your gateway is directly between your browser and the gateway itself. There is a hop in between, our AWS server, but that just adds an extra wrapper on the outside between itself and your gateway.

So in order to make a wildcard certificate work with the current setup, the same private key would have to be distributed to every single gateway. Sharing private keys isn't recommended even when you control all of the infrastructure yourself, so it's definitely not safe when the gateways are completely out of our control. If everyone has the same private key for a generic `*.mozilla-iot.org` domain, they would be able to impersonate `api.mozilla-iot.org` (or anyone else), for instance.

**Comment by benfrancis** [comment]
I agree, it's better that each gateway has its own certificate, at least with the current setup.
