### ISSUE TITLE
WiFi Access Point

### ISSUE THREAD

**Issue by nithyanantham** [mozilla-iot/gateway#895]
As a user I want configure my gateway to support both station and access point mode so that I can connect all my edge device/sensors to gateway (Raspberry Pi) directly.

**Comment by mrstegeman** [comment]
Requires #423

**Comment by dhylands** [comment]
It would also be useful for demos where internet access is otherwise unavailable.

**Comment by nullr0ute** [comment]
If we use the NetworkManager API to do this is can be distribution agnostic.

**Comment by flatsiedatsie** [comment]
As a side note: in my use case the Mozilla Gateway will never connect to the home network or the internet. Never. The only user interaction will be via voice control and via a connected tablet which will be wall mounted.

This might sound extreme now, but I suspect it will become a much more common practice in the common years (after a few more scandals).

Completely air-gapping the system improves security tremendously. It also forces all devices to still work without access to the cloud, which post-GDPR should be best practice.

**Comment by kgiori** [comment]
For this issue, I can imagine three possible network states for the Things Gateway:

1. **Wi-Fi Client**
Default setup assumption to date, up to gateway 0.6. Can also skip and connect to a local network via Ethernet, where Wi-Fi radio is off.
2. **Wi-Fi Access Point**
Acts as a passthrough or bridge. The gateway receives an IP address via Ethernet port from an upstream router that serves up DHCP IP addresses. Other Wi-Fi devices can either connect to the Things Gateway or directly to the upstream router. Both the gateway and the Wi-Fi clients that connect to it receive an IP address in the same subnet from the upstream router. Net result is gateway is not doing NAT because it is not serving its own subnet.
3. **Wi-Fi Router**
Gateway serves up DHCP IP addresses on its own subnet, such as 192.168.220.*. However in this case, the Ethernet port is a WAN port with its own IP address from a different subnet that was given by the upstream router, and the gateway does NAT'd routing. Potential user setup problem if the home router happens to be configured on the same subnet of 192.168.220.1 -- maybe there's a way to catch that issue on initial setup and automatically adjust the gateway subnet though.

In the future, we could add Wi-Fi mesh as an option too. But there's not one standard here. Might need to include several mesh techniques such as 11s, WFA EasyMesh (which is actually "managed 4-addr WDS"), or other mesh protocols.

**Comment by flatsiedatsie** [comment]
@kgiori I would also add "completely stand alone install", although you could say it's a subset of 3.

**Comment by flatsiedatsie** [comment]
Another example of setting the Mozilla Gateway as the connection point for all wifi and bluetooth connected smart devices is that it could allow for extra security (perhaps as an add-on, in an app store). 

A lot of deep learning based threat detection devices and software is coming to market, including open source varieties.

Examples in this direction:

https://youtu.be/Nc0xrzCjyVo
https://suricata-ids.org/
https://iot-inspector.princeton.edu/
https://github.com/Or3stis/apparatus
https://www.getcujo.com/
Hardware:
https://www.kickstarter.com/projects/eblocker/the-first-plug-and-play-privacy-solution-for-all-y
https://www.mbreviews.com/cujo-vs-pfsense-vs-router-firewall/

**Comment by benfrancis** [comment]
@flatsiedatsie Yes, this is exactly the kind of thing we hope to do once we have the gateway software is running on wireless routers.

**Comment by flatsiedatsie** [comment]
Very cool!
